<?php

namespace Thirty98\Seeder\States\Louisiana\POS;

use Thirty98\API\Stdlib\AbstractDatabaseSeeder;
use Illuminate\Support\Facades\DB;
use Thirty98\Models\POSLAStatePlateCategory;

class StatePlateCodeCategorySeeder extends AbstractDatabaseSeeder
{
    public $state_code = 'LA';
    protected $table_name = 'pos_la_state_plate_code_categories';

    protected function executeSeeder()
    {
        foreach($this->getCategory() as $category) {
            $slug_category = $this->slugit($category);

            $exists = DB::table($this->table_name)->where('slug', $slug_category)
                ->first();

            if(!$exists) {
                POSLAStatePlateCategory::insert([
                    'name' => $category,
                    'slug' => $slug_category
                ]);
            }
        }
    }

    protected function getCategory()
    {
        return [
            "2010 New Orleans Saints",
            "4 Yr. Ident-Public-Non-State",
            "4 Yr. Ident-Public-State",
            "4-H Club",
            "Afghan Campaign Vet",
            "Afghan War Veteran",
            "Afghanistan Campaign Veteran",
            "Agriculture",
            "Air Force",
            "Air Force Active Duty",
            "Ambulance",
            "America's Wetlands",
            "American Wetland",
            "Animal Friendly",
            "Antique",
            "Antique Personalized",
            "Apportioned",
            "Apportioned Lifetime",
            "Army",
            "Army Active Duty",
            "Army Airborne",
            "Army Truck",
            "Bell South",
            "Bell South Volunteers",
            "Black Bear",
            "Boat",
            "Boat-Public-Non-State",
            "Boat-Public-State",
            "Books For School",
            "Books For School Children",
            "Books for School",
            "Boy Scouts of America",
            "Breast Cancer Awareness",
            "CG Active Duty",
            "Camp Woodman",
            "Charles Dunbar",
            "Chez Nous Autres",
            "Child Safety",
            "Choose Life",
            "City Use",
            "Civil Air Patrol",
            "Civil Law Notary",
            "Coast Guard",
            "Coast Guard Active Duty",
            "Coastal Conservation",
            "Com. Law Enfc. Offc.",
            "Comm'd Law Enforc. Officer",
            "Commercial",
            "Commercial Auto",
            "Commercial Handicap",
            "Commercial Limo",
            "Commissioned Law Enfor Police",
            "Common Carrier-Apportioned",
            "Cong Medal Honor",
            "Cong Medal of Honor",
            "Congressional Medal of Honor",
            "Cultural Economy",
            "D Storm Air Force",
            "D Storm Coast Guard",
            "Dealer",
            "Desert Storm Air Force",
            "Desert Storm Army",
            "Desert Storm Coast Guard",
            "Desert Storm Marine",
            "Desert Storm Navy",
            "Disabled Veteran",
            "Disabled Veteteran Motorcycle",
            "Ducks Unlimited",
            "EMT",
            "Educator",
            "Emergency Medical Tech",
            "Emergency Medical Technician",
            "Environmental Educ",
            "Environmental Education",
            "Esther Grand",
            "Esther Grand Eastern Star",
            "Family Police Killed",
            "Family of Police",
            "Family of Police Killed",
            "Farm",
            "Farm Semi",
            "Farm-up",
            "Feeding Hope",
            "Forest",
            "Frat Order of Police",
            "Fraternal Order Police",
            "Fraternal Order of Police",
            "Full Gospel",
            "Girl Scout",
            "Gold Star",
            "Gold Star Motorcycle",
            "Gov's Staff Private",
            "Gov's Staff Public",
            "Governor's Staff Private",
            "Governor's Staff Public",
            "Grand Lodge LA",
            "Gravel",
            "Grotto",
            "Ham",
            "Ham Bus",
            "Ham Handicap",
            "Ham Truck",
            "Handicap",
            "Handicap Farm",
            "Handicap Free",
            "Handicap Truck",
            "Handicap-Commercial",
            "Handicap-Free",
            "Handicap-Veteran Exempt",
            "Handicap-Veterans Exempt",
            "Hearing Impaired",
            "Hearing Impaired-Commercial",
            "Hearing Impaired-Veteran Exempt",
            "Hearing Impaired-Vets Exempt",
            "Hearse Commercial",
            "Hearse Limo",
            "Hearse Private",
            "Hire Bus Apportioned",
            "Hire Bus-City",
            "Hire Bus-State",
            "Hire I-Limo",
            "Hire Passenger",
            "Hire Passenger (Taxi)",
            "Hire Passenger-City",
            "Hire Passenger-State",
            "Hire Taxi",
            "Hire-Limo Commercial",
            "Hire-Limo Private",
            "Honorary Consul",
            "Hospice",
            "House Trailer",
            "I'm Cajun",
            "I'm Creole",
            "Ident-1 Year",
            "Ident-4 Year",
            "Ident-Lifetime",
            "Ident-Public-Non-State-Perm",
            "Ident-Public-State-Perm",
            "Immovable",
            "In God We Trust",
            "Institutional Handicap",
            "Iraq Campaign Veteran",
            "Iraq War Veteran",
            "Knights of Columbus",
            "Knights of Peter Claver",
            "Korean Air Force",
            "Korean Army",
            "Korean Coast Guard",
            "Korean Defense Service Medal",
            "Korean Defense Service Medal 10001-16000 l",
            "Korean Marine",
            "Korean Navy",
            "Korean War Air Force",
            "Korean War Army",
            "Korean War Coast Guard",
            "Korean War Marine",
            "Korean War Navy",
            "LA Black Bear",
            "LA Educator",
            "LA Nurses Foundation",
            "LA Organ Donation",
            "LA Seafood",
            "LA Thanks You",
            "Laos War Veteran",
            "Large Mouth Bass",
            "Largemouth Bass",
            "Legislator",
            "Light Semi",
            "Light Semi Public-Non-State",
            "Light Semi Public-State",
            "Lions International",
            "Logo Plates- Carrier Apportioned",
            "Logo Plates-Apportioned Vehicles",
            "Louisiana Black Bear",
            "Louisiana Educator",
            "Louisiana Notary",
            "Louisiana Seafood",
            "Low Speed Auto",
            "M'cycle Awareness",
            "March of Dimes",
            "Marine",
            "Marine Active Duty",
            "Marine Corp League",
            "Marine Truck",
            "Masonic Blue",
            "Merchant Marine",
            "Mini Truck",
            "Motorcycle Awareness",
            "N.O. Horse Carriage",
            "N.O. Limo",
            "N.O. Pedicab",
            "N.O. Taxi",
            "Name",
            "National Guard",
            "Native American",
            "Navy",
            "Navy Active Duty",
            "Navy Truck",
            "Nurse's Foundation",
            "Nurses Foundation",
            "Off Road Vehicle",
            "Old Antique",
            "Old Antique Motorcycle Plate",
            "Old Antique Plate",
            "Pearl Habor",
            "Pearl Harbor",
            "Pearl Harbor Survivor",
            "Personalized",
            "Personalized Commercial",
            "Personalized Dealer",
            "Personalized Handicap",
            "Personalized Truck",
            "Peter Claver",
            "Prestige Handicap",
            "Prestige1 Auto",
            "Prestige1 Bus",
            "Prestige1 Motorcycle",
            "Prestige1 Truck",
            "Priv-Public-Non-State",
            "Private",
            "Private Apportioned",
            "Private Bus",
            "Private Bus-Non-State",
            "Private Bus-Priv-Public-Non-State",
            "Private Bus-Public-State",
            "Private Bus-State",
            "Private Shriner",
            "Private Truck",
            "Private-Ambulance",
            "Private-Commercial",
            "Private-Driver Ed",
            "Private-Public-Non-State",
            "Private-Public-State",
            "Private-Veteran Exempt",
            "Prof.Firefighter",
            "Professional Firefighter",
            "Protect Our Forests",
            "Public FR Private Bus",
            "Public Handicap-Non-State",
            "Public Handicap-State",
            "Public NS Private Bus",
            "Public Pvt Trk-NS",
            "Public Pvt Trk-ST",
            "Public ST Private Bus",
            "Public-Handicap-Non-State",
            "Public-Handicap-State",
            "Public-Non-State",
            "Public-Non-State-Decal",
            "Public-State",
            "Public-State-Decal",
            "Purple Heart",
            "Quail Unlimited",
            "R-Limo Commercial",
            "R-Limo Private",
            "Rare/Endangered",
            "Rare/Endangered Species",
            "Relay For Life",
            "Reserve Forces",
            "Reserve Forces Retired",
            "Retired Air Force",
            "Retired Army",
            "Retired Coast Guard",
            "Retired Firefighter",
            "Retired Law Enforcement",
            "Retired Law Motorcycle",
            "Retired Law Officer",
            "Retired Marine",
            "Retired Navy",
            "Retired Reserve Forces",
            "Rotary District",
            "Save the Honeybee",
            "School Bus",
            "School Bus-Public-Non-State",
            "School Bus-Public-State",
            "Senior Heritage",
            "Seniors Our Heritage",
            "Share The Road",
            "Shriner",
            "Sons of Confederate",
            "Sons of Confederate Veterans",
            "Special Olympics",
            "Special Public Bus",
            "Special Public Entity Plate",
            "Special Public Plate",
            "Special Public Trailer Plate",
            "St. Jude Children",
            "Street Cruiser",
            "Street Rod",
            "Supp. Our Troops",
            "Supp.Our Troops",
            "Support Our Troops",
            "Support Our Veterans",
            "Support Veterans",
            "Tow Carrier",
            "Tow/Recovery",
            "Town of Ball",
            "Trust God",
            "U.S. Army Airborne",
            "U.S. Congressman",
            "U.S. Senator",
            "Undefined",
            "University/High Sch",
            "University/High Schools",
            "Unlocking Autism",
            "Veterans Exempt",
            "Viet Coast Guard",
            "Vietnam Air Force",
            "Vietnam Army",
            "Vietnam Coast Guard",
            "Vietnam Marine",
            "Vietnam Navy",
            "Volunteer Firefighter",
            "WWOZ Groove",
            "WWOZ Groove Bus",
            "WWOZ Groove Truck",
            "WWOZ Truck",
            "Wash Artillery",
            "Washington Artillery",
            "Water Waste",
            "White Tail Deer",
            "Wild Dolphins",
            "Wild Turkey",
            "Wild Turkey Federation",
            "World War II",
            "XPOW",
            "ZULU Club",
            "ZULU Social Aid Club"
        ];
    }

}
