-- MySQL Script generated by MySQL Workbench
-- 09/04/15 01:50:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `states` ;

CREATE TABLE IF NOT EXISTS `states` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(150) NOT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `deleted_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fees` ;

CREATE TABLE IF NOT EXISTS `fees` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `note` VARCHAR(140) NOT NULL COMMENT '',
  `type` ENUM('fee', 'tax', 'penalty') NOT NULL DEFAULT 'fee' COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `deleted_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `counties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `counties` ;

CREATE TABLE IF NOT EXISTS `counties` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `state_id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(150) NOT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `deleted_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cities` ;

CREATE TABLE IF NOT EXISTS `cities` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `county_id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `deleted_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories` ;

CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `deleted_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `types` ;

CREATE TABLE IF NOT EXISTS `types` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `deleted_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categories_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories_types` ;

CREATE TABLE IF NOT EXISTS `categories_types` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `category_id` INT NOT NULL COMMENT '',
  `type_id` INT NOT NULL COMMENT '',
  `start_date` DATE NULL COMMENT '',
  `end_date` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fees_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fees_states` ;

CREATE TABLE IF NOT EXISTS `fees_states` (
  `state_id` INT NOT NULL COMMENT '',
  `fee_id` INT NOT NULL COMMENT '',
  `category_type_id` INT NOT NULL COMMENT '',
  `amount` DECIMAL(11,2) NULL COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `counties_fees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `counties_fees` ;

CREATE TABLE IF NOT EXISTS `counties_fees` (
  `county_id` INT NOT NULL COMMENT '',
  `fee_id` INT NOT NULL COMMENT '',
  `category_type_id` INT NOT NULL COMMENT '',
  `amount` DECIMAL(11,2) NULL COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cities_fees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cities_fees` ;

CREATE TABLE IF NOT EXISTS `cities_fees` (
  `city_id` INT NOT NULL COMMENT '',
  `fee_id` INT NOT NULL COMMENT '',
  `category_type_id` INT NOT NULL COMMENT '',
  `amount` DECIMAL(11,2) NULL COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tx_weightfees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tx_weightfees` ;

CREATE TABLE IF NOT EXISTS `tx_weightfees` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `state_id` INT NOT NULL COMMENT '',
  `fee_id` INT NOT NULL COMMENT '',
  `weight_class` INT NOT NULL COMMENT '',
  `min_weight` INT NOT NULL COMMENT '',
  `max_weight` INT NOT NULL COMMENT '',
  `amount` DECIMAL(11,2) NOT NULL COMMENT '',
  `start_date` DATE NULL COMMENT '',
  `end_date` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tx_inspfees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tx_inspfees` ;

CREATE TABLE IF NOT EXISTS `tx_inspfees` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `county_id` INT NOT NULL COMMENT '',
  `NEW_MV_2YR` DECIMAL(11,2) NOT NULL COMMENT '',
  `USED_MV_1YR` DECIMAL(11,2) NOT NULL COMMENT '',
  `COMMERCIAL` DECIMAL(11,2) NOT NULL COMMENT '',
  `MOTORCYCLE` DECIMAL(11,2) NOT NULL COMMENT '',
  `TRAILER` DECIMAL(11,2) NOT NULL COMMENT '',
  `START_DT` DATE NOT NULL COMMENT '',
  `END_DT` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ttltypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttltypes` ;

CREATE TABLE IF NOT EXISTS `ttltypes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(5) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `states_ttltypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `states_ttltypes` ;

CREATE TABLE IF NOT EXISTS `states_ttltypes` (
  `state_id` INT NOT NULL COMMENT '',
  `ttltype_id` INT NOT NULL COMMENT '',
  `fee_id` INT NULL COMMENT '',
  `value` TINYINT NOT NULL DEFAULT 0 COMMENT '0 = NO\n1 = YES')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
