<?php

namespace Thirty98\Seeder\States\Texas;

use Thirty98\API\Stdlib\Seeders\AbstractCitySeeder;

class CitySeeder extends AbstractCitySeeder
{
    public $state = 'TX';
    
    protected function getCities()
    {
        return [
            ["name" => "CAYUGA", "county" => "ANDERSON"],
            ["name" => "ELKHART", "county" => "ANDERSON"],
            ["name" => "FRANKSTON", "county" => "ANDERSON"],
            ["name" => "MONTALBA", "county" => "ANDERSON"],
            ["name" => "NECHES", "county" => "ANDERSON"],
            ["name" => "PALESTINE", "county" => "ANDERSON"],
            ["name" => "TENNESSEE COLONY", "county" => "ANDERSON"],
            ["name" => "ANDREWS", "county" => "ANDREWS"],
            ["name" => "DIBOLL", "county" => "ANGELINA"],
            ["name" => "HUNTINGTON", "county" => "ANGELINA"],
            ["name" => "LUFKIN", "county" => "ANGELINA"],
            ["name" => "POLLOK", "county" => "ANGELINA"],
            ["name" => "ZAVALLA", "county" => "ANGELINA"],
            ["name" => "FULTON", "county" => "ARANSAS"],
            ["name" => "ROCKPORT", "county" => "ARANSAS"],
            ["name" => "ARCHER CITY", "county" => "ARCHER"],
            ["name" => "HOLLIDAY", "county" => "ARCHER"],
            ["name" => "MEGARGEL", "county" => "ARCHER"],
            ["name" => "SCOTLAND", "county" => "ARCHER"],
            ["name" => "WINDTHORST", "county" => "ARCHER"],
            ["name" => "CLAUDE", "county" => "ARMSTRONG"],
            ["name" => "WAYSIDE", "county" => "ARMSTRONG"],
            ["name" => "CAMPBELLTON", "county" => "ATASCOSA"],
            ["name" => "CHARLOTTE", "county" => "ATASCOSA"],
            ["name" => "CHRISTINE", "county" => "ATASCOSA"],
            ["name" => "JOURDANTON", "county" => "ATASCOSA"],
            ["name" => "LEMING", "county" => "ATASCOSA"],
            ["name" => "LYTLE", "county" => "ATASCOSA"],
            ["name" => "PEGGY", "county" => "ATASCOSA"],
            ["name" => "PLEASANTON", "county" => "ATASCOSA"],
            ["name" => "POTEET", "county" => "ATASCOSA"],
            ["name" => "BELLVILLE", "county" => "AUSTIN"],
            ["name" => "BLEIBLERVILLE", "county" => "AUSTIN"],
            ["name" => "CAT SPRING", "county" => "AUSTIN"],
            ["name" => "INDUSTRY", "county" => "AUSTIN"],
            ["name" => "KENNEY", "county" => "AUSTIN"],
            ["name" => "NEW ULM", "county" => "AUSTIN"],
            ["name" => "SAN FELIPE", "county" => "AUSTIN"],
            ["name" => "SEALY", "county" => "AUSTIN"],
            ["name" => "WALLIS", "county" => "AUSTIN"],
            ["name" => "ENOCHS", "county" => "BAILEY"],
            ["name" => "MAPLE", "county" => "BAILEY"],
            ["name" => "MULESHOE", "county" => "BAILEY"],
            ["name" => "BANDERA", "county" => "BANDERA"],
            ["name" => "LAKEHILLS", "county" => "BANDERA"],
            ["name" => "MEDINA", "county" => "BANDERA"],
            ["name" => "PIPE CREEK", "county" => "BANDERA"],
            ["name" => "TARPLEY", "county" => "BANDERA"],
            ["name" => "VANDERPOOL", "county" => "BANDERA"],
            ["name" => "BASTROP", "county" => "BASTROP"],
            ["name" => "CEDAR CREEK", "county" => "BASTROP"],
            ["name" => "ELGIN", "county" => "BASTROP"],
            ["name" => "MC DADE", "county" => "BASTROP"],
            ["name" => "PAIGE", "county" => "BASTROP"],
            ["name" => "RED ROCK", "county" => "BASTROP"],
            ["name" => "ROSANKY", "county" => "BASTROP"],
            ["name" => "SMITHVILLE", "county" => "BASTROP"],
            ["name" => "SEYMOUR", "county" => "BAYLOR"],
            ["name" => "BEEVILLE", "county" => "BEE"],
            ["name" => "MINERAL", "county" => "BEE"],
            ["name" => "NORMANNA", "county" => "BEE"],
            ["name" => "PAWNEE", "county" => "BEE"],
            ["name" => "PETTUS", "county" => "BEE"],
            ["name" => "SKIDMORE", "county" => "BEE"],
            ["name" => "TULETA", "county" => "BEE"],
            ["name" => "TYNAN", "county" => "BEE"],
            ["name" => "BARTLETT", "county" => "BELL"],
            ["name" => "BELTON", "county" => "BELL"],
            ["name" => "FORT HOOD", "county" => "BELL"],
            ["name" => "HARKER HEIGHTS", "county" => "BELL"],
            ["name" => "HEIDENHEIMER", "county" => "BELL"],
            ["name" => "HOLLAND", "county" => "BELL"],
            ["name" => "KILLEEN", "county" => "BELL"],
            ["name" => "LITTLE RIVER ACADEMY", "county" => "BELL"],
            ["name" => "NOLANVILLE", "county" => "BELL"],
            ["name" => "PENDLETON", "county" => "BELL"],
            ["name" => "ROGERS", "county" => "BELL"],
            ["name" => "SALADO", "county" => "BELL"],
            ["name" => "TEMPLE", "county" => "BELL"],
            ["name" => "TROY", "county" => "BELL"],
            ["name" => "ADKINS", "county" => "BEXAR"],
            ["name" => "ATASCOSA", "county" => "BEXAR"],
            ["name" => "CONVERSE", "county" => "BEXAR"],
            ["name" => "ELMENDORF", "county" => "BEXAR"],
            ["name" => "HELOTES", "county" => "BEXAR"],
            ["name" => "LACKLAND A F B", "county" => "BEXAR"],
            ["name" => "MACDONA", "county" => "BEXAR"],
            ["name" => "RANDOLPH AFB", "county" => "BEXAR"],
            ["name" => "SAINT HEDWIG", "county" => "BEXAR"],
            ["name" => "SAN ANTONIO", "county" => "BEXAR"],
            ["name" => "SOMERSET", "county" => "BEXAR"],
            ["name" => "UNIVERSAL CITY", "county" => "BEXAR"],
            ["name" => "VON ORMY", "county" => "BEXAR"],
            ["name" => "BLANCO", "county" => "BLANCO"],
            ["name" => "HYE", "county" => "BLANCO"],
            ["name" => "JOHNSON CITY", "county" => "BLANCO"],
            ["name" => "ROUND MOUNTAIN", "county" => "BLANCO"],
            ["name" => "GAIL", "county" => "BORDEN"],
            ["name" => "CLIFTON", "county" => "BOSQUE"],
            ["name" => "CRANFILLS GAP", "county" => "BOSQUE"],
            ["name" => "IREDELL", "county" => "BOSQUE"],
            ["name" => "KOPPERL", "county" => "BOSQUE"],
            ["name" => "LAGUNA PARK", "county" => "BOSQUE"],
            ["name" => "MERIDIAN", "county" => "BOSQUE"],
            ["name" => "MORGAN", "county" => "BOSQUE"],
            ["name" => "VALLEY MILLS", "county" => "BOSQUE"],
            ["name" => "WALNUT SPRINGS", "county" => "BOSQUE"],
            ["name" => "DE KALB", "county" => "BOWIE"],
            ["name" => "HOOKS", "county" => "BOWIE"],
            ["name" => "MAUD", "county" => "BOWIE"],
            ["name" => "NASH", "county" => "BOWIE"],
            ["name" => "NEW BOSTON", "county" => "BOWIE"],
            ["name" => "REDWATER", "county" => "BOWIE"],
            ["name" => "SIMMS", "county" => "BOWIE"],
            ["name" => "TEXARKANA", "county" => "BOWIE"],
            ["name" => "ALVIN", "county" => "BRAZORIA"],
            ["name" => "ANGLETON", "county" => "BRAZORIA"],
            ["name" => "BRAZORIA", "county" => "BRAZORIA"],
            ["name" => "CLUTE", "county" => "BRAZORIA"],
            ["name" => "DAMON", "county" => "BRAZORIA"],
            ["name" => "DANBURY", "county" => "BRAZORIA"],
            ["name" => "DANCIGER", "county" => "BRAZORIA"],
            ["name" => "FREEPORT", "county" => "BRAZORIA"],
            ["name" => "LAKE JACKSON", "county" => "BRAZORIA"],
            ["name" => "LIVERPOOL", "county" => "BRAZORIA"],
            ["name" => "MANVEL", "county" => "BRAZORIA"],
            ["name" => "OLD OCEAN", "county" => "BRAZORIA"],
            ["name" => "PEARLAND", "county" => "BRAZORIA"],
            ["name" => "ROSHARON", "county" => "BRAZORIA"],
            ["name" => "SWEENY", "county" => "BRAZORIA"],
            ["name" => "WEST COLUMBIA", "county" => "BRAZORIA"],
            ["name" => "BRYAN", "county" => "BRAZOS"],
            ["name" => "COLLEGE STATION", "county" => "BRAZOS"],
            ["name" => "KURTEN", "county" => "BRAZOS"],
            ["name" => "MILLICAN", "county" => "BRAZOS"],
            ["name" => "WELLBORN", "county" => "BRAZOS"],
            ["name" => "ALPINE", "county" => "BREWSTER"],
            ["name" => "BIG BEND NATIONAL PARK", "county" => "BREWSTER"],
            ["name" => "MARATHON", "county" => "BREWSTER"],
            ["name" => "TERLINGUA", "county" => "BREWSTER"],
            ["name" => "QUITAQUE", "county" => "BRISCOE"],
            ["name" => "SILVERTON", "county" => "BRISCOE"],
            ["name" => "ENCINO", "county" => "BROOKS"],
            ["name" => "FALFURRIAS", "county" => "BROOKS"],
            ["name" => "BANGS", "county" => "BROWN"],
            ["name" => "BLANKET", "county" => "BROWN"],
            ["name" => "BROOKESMITH", "county" => "BROWN"],
            ["name" => "BROWNWOOD", "county" => "BROWN"],
            ["name" => "EARLY", "county" => "BROWN"],
            ["name" => "MAY", "county" => "BROWN"],
            ["name" => "ZEPHYR", "county" => "BROWN"],
            ["name" => "CALDWELL", "county" => "BURLESON"],
            ["name" => "CHRIESMAN", "county" => "BURLESON"],
            ["name" => "DEANVILLE", "county" => "BURLESON"],
            ["name" => "LYONS", "county" => "BURLESON"],
            ["name" => "SNOOK", "county" => "BURLESON"],
            ["name" => "SOMERVILLE", "county" => "BURLESON"],
            ["name" => "BERTRAM", "county" => "BURNET"],
            ["name" => "BRIGGS", "county" => "BURNET"],
            ["name" => "BURNET", "county" => "BURNET"],
            ["name" => "MARBLE FALLS", "county" => "BURNET"],
            ["name" => "DALE", "county" => "CALDWELL"],
            ["name" => "FENTRESS", "county" => "CALDWELL"],
            ["name" => "LOCKHART", "county" => "CALDWELL"],
            ["name" => "LULING", "county" => "CALDWELL"],
            ["name" => "MARTINDALE", "county" => "CALDWELL"],
            ["name" => "MAXWELL", "county" => "CALDWELL"],
            ["name" => "PRAIRIE LEA", "county" => "CALDWELL"],
            ["name" => "POINT COMFORT", "county" => "CALHOUN"],
            ["name" => "PORT LAVACA", "county" => "CALHOUN"],
            ["name" => "PORT O CONNOR", "county" => "CALHOUN"],
            ["name" => "SEADRIFT", "county" => "CALHOUN"],
            ["name" => "BAIRD", "county" => "CALLAHAN"],
            ["name" => "CLYDE", "county" => "CALLAHAN"],
            ["name" => "CROSS PLAINS", "county" => "CALLAHAN"],
            ["name" => "PUTNAM", "county" => "CALLAHAN"],
            ["name" => "BROWNSVILLE", "county" => "CAMERON"],
            ["name" => "COMBES", "county" => "CAMERON"],
            ["name" => "HARLINGEN", "county" => "CAMERON"],
            ["name" => "LA FERIA", "county" => "CAMERON"],
            ["name" => "LOS FRESNOS", "county" => "CAMERON"],
            ["name" => "LOS INDIOS", "county" => "CAMERON"],
            ["name" => "LOZANO", "county" => "CAMERON"],
            ["name" => "OLMITO", "county" => "CAMERON"],
            ["name" => "PORT ISABEL", "county" => "CAMERON"],
            ["name" => "RIO HONDO", "county" => "CAMERON"],
            ["name" => "SAN BENITO", "county" => "CAMERON"],
            ["name" => "SANTA MARIA", "county" => "CAMERON"],
            ["name" => "SANTA ROSA", "county" => "CAMERON"],
            ["name" => "SOUTH PADRE ISLAND", "county" => "CAMERON"],
            ["name" => "LEESBURG", "county" => "CAMP"],
            ["name" => "PITTSBURG", "county" => "CAMP"],
            ["name" => "GROOM", "county" => "CARSON"],
            ["name" => "PANHANDLE", "county" => "CARSON"],
            ["name" => "SKELLYTOWN", "county" => "CARSON"],
            ["name" => "WHITE DEER", "county" => "CARSON"],
            ["name" => "ATLANTA", "county" => "CASS"],
            ["name" => "AVINGER", "county" => "CASS"],
            ["name" => "BIVINS", "county" => "CASS"],
            ["name" => "BLOOMBURG", "county" => "CASS"],
            ["name" => "DOUGLASSVILLE", "county" => "CASS"],
            ["name" => "HUGHES SPRINGS", "county" => "CASS"],
            ["name" => "KILDARE", "county" => "CASS"],
            ["name" => "LINDEN", "county" => "CASS"],
            ["name" => "MARIETTA", "county" => "CASS"],
            ["name" => "MC LEOD", "county" => "CASS"],
            ["name" => "QUEEN CITY", "county" => "CASS"],
            ["name" => "DIMMITT", "county" => "CASTRO"],
            ["name" => "HART", "county" => "CASTRO"],
            ["name" => "NAZARETH", "county" => "CASTRO"],
            ["name" => "SUMMERFIELD", "county" => "CASTRO"],
            ["name" => "ANAHUAC", "county" => "CHAMBERS"],
            ["name" => "BAYTOWN", "county" => "CHAMBERS"],
            ["name" => "HANKAMER", "county" => "CHAMBERS"],
            ["name" => "MONT BELVIEU", "county" => "CHAMBERS"],
            ["name" => "STOWELL", "county" => "CHAMBERS"],
            ["name" => "WALLISVILLE", "county" => "CHAMBERS"],
            ["name" => "WINNIE", "county" => "CHAMBERS"],
            ["name" => "BAYTOWN", "county" => "CHAMBERS"],
            ["name" => "BAYTOWN", "county" => "CHAMBERS"],
            ["name" => "ALTO", "county" => "CHEROKEE"],
            ["name" => "CUNEY", "county" => "CHEROKEE"],
            ["name" => "GALLATIN", "county" => "CHEROKEE"],
            ["name" => "JACKSONVILLE", "county" => "CHEROKEE"],
            ["name" => "MAYDELLE", "county" => "CHEROKEE"],
            ["name" => "NEW SUMMERFIELD", "county" => "CHEROKEE"],
            ["name" => "REKLAW", "county" => "CHEROKEE"],
            ["name" => "RUSK", "county" => "CHEROKEE"],
            ["name" => "WELLS", "county" => "CHEROKEE"],
            ["name" => "CHILDRESS", "county" => "CHILDRESS"],
            ["name" => "TELL", "county" => "CHILDRESS"],
            ["name" => "TELL", "county" => "CLAY"],
            ["name" => "BELLEVUE", "county" => "CLAY"],
            ["name" => "BLUEGROVE", "county" => "CLAY"],
            ["name" => "BYERS", "county" => "CLAY"],
            ["name" => "HENRIETTA", "county" => "CLAY"],
            ["name" => "PETROLIA", "county" => "CLAY"],
            ["name" => "BLEDSOE", "county" => "COCHRAN"],
            ["name" => "MORTON", "county" => "COCHRAN"],
            ["name" => "WHITEFACE", "county" => "COCHRAN"],
            ["name" => "BRONTE", "county" => "COKE"],
            ["name" => "ROBERT LEE", "county" => "COKE"],
            ["name" => "SILVER", "county" => "COKE"],
            ["name" => "TENNYSON", "county" => "COKE"],
            ["name" => "BURKETT", "county" => "COLEMAN"],
            ["name" => "COLEMAN", "county" => "COLEMAN"],
            ["name" => "GOLDSBORO", "county" => "COLEMAN"],
            ["name" => "GOULDBUSK", "county" => "COLEMAN"],
            ["name" => "NOVICE", "county" => "COLEMAN"],
            ["name" => "ROCKWOOD", "county" => "COLEMAN"],
            ["name" => "SANTA ANNA", "county" => "COLEMAN"],
            ["name" => "TALPA", "county" => "COLEMAN"],
            ["name" => "VALERA", "county" => "COLEMAN"],
            ["name" => "VOSS", "county" => "COLEMAN"],
            ["name" => "ALLEN", "county" => "COLLIN"],
            ["name" => "ANNA", "county" => "COLLIN"],
            ["name" => "BLUE RIDGE", "county" => "COLLIN"],
            ["name" => "CELINA", "county" => "COLLIN"],
            ["name" => "COPEVILLE", "county" => "COLLIN"],
            ["name" => "DALLAS", "county" => "COLLIN"],
            ["name" => "FARMERSVILLE", "county" => "COLLIN"],
            ["name" => "FRISCO", "county" => "COLLIN"],
            ["name" => "JOSEPHINE", "county" => "COLLIN"],
            ["name" => "LAVON", "county" => "COLLIN"],
            ["name" => "MCKINNEY", "county" => "COLLIN"],
            ["name" => "MELISSA", "county" => "COLLIN"],
            ["name" => "NEVADA", "county" => "COLLIN"],
            ["name" => "PLANO", "county" => "COLLIN"],
            ["name" => "PRINCETON", "county" => "COLLIN"],
            ["name" => "PROSPER", "county" => "COLLIN"],
            ["name" => "WESTMINSTER", "county" => "COLLIN"],
            ["name" => "WESTON", "county" => "COLLIN"],
            ["name" => "WYLIE", "county" => "COLLIN"],
            ["name" => "DODSON", "county" => "COLLINGSWORTH"],
            ["name" => "QUAIL", "county" => "COLLINGSWORTH"],
            ["name" => "SAM NORWOOD", "county" => "COLLINGSWORTH"],
            ["name" => "WELLINGTON", "county" => "COLLINGSWORTH"],
            ["name" => "ALLEYTON", "county" => "COLORADO"],
            ["name" => "ALTAIR", "county" => "COLORADO"],
            ["name" => "COLUMBUS", "county" => "COLORADO"],
            ["name" => "EAGLE LAKE", "county" => "COLORADO"],
            ["name" => "GARWOOD", "county" => "COLORADO"],
            ["name" => "GLIDDEN", "county" => "COLORADO"],
            ["name" => "NADA", "county" => "COLORADO"],
            ["name" => "OAKLAND", "county" => "COLORADO"],
            ["name" => "ROCK ISLAND", "county" => "COLORADO"],
            ["name" => "SHERIDAN", "county" => "COLORADO"],
            ["name" => "WEIMAR", "county" => "COLORADO"],
            ["name" => "BULVERDE", "county" => "COMAL"],
            ["name" => "CANYON LAKE", "county" => "COMAL"],
            ["name" => "FISCHER", "county" => "COMAL"],
            ["name" => "NEW BRAUNFELS", "county" => "COMAL"],
            ["name" => "SAN ANTONIO", "county" => "COMAL"],
            ["name" => "SPRING BRANCH", "county" => "COMAL"],
            ["name" => "COMANCHE", "county" => "COMANCHE"],
            ["name" => "DE LEON", "county" => "COMANCHE"],
            ["name" => "ENERGY", "county" => "COMANCHE"],
            ["name" => "GUSTINE", "county" => "COMANCHE"],
            ["name" => "PROCTOR", "county" => "COMANCHE"],
            ["name" => "SIDNEY", "county" => "COMANCHE"],
            ["name" => "EDEN", "county" => "CONCHO"],
            ["name" => "EOLA", "county" => "CONCHO"],
            ["name" => "LOWAKE", "county" => "CONCHO"],
            ["name" => "MILLERSVIEW", "county" => "CONCHO"],
            ["name" => "PAINT ROCK", "county" => "CONCHO"],
            ["name" => "ERA", "county" => "COOKE"],
            ["name" => "GAINESVILLE", "county" => "COOKE"],
            ["name" => "LINDSAY", "county" => "COOKE"],
            ["name" => "MUENSTER", "county" => "COOKE"],
            ["name" => "MYRA", "county" => "COOKE"],
            ["name" => "ROSSTON", "county" => "COOKE"],
            ["name" => "VALLEY VIEW", "county" => "COOKE"],
            ["name" => "COPPERAS COVE", "county" => "CORYELL"],
            ["name" => "EVANT", "county" => "CORYELL"],
            ["name" => "FLAT", "county" => "CORYELL"],
            ["name" => "GATESVILLE", "county" => "CORYELL"],
            ["name" => "JONESBORO", "county" => "CORYELL"],
            ["name" => "MOUND", "county" => "CORYELL"],
            ["name" => "OGLESBY", "county" => "CORYELL"],
            ["name" => "PURMELA", "county" => "CORYELL"],
            ["name" => "CEE VEE", "county" => "COTTLE"],
            ["name" => "PADUCAH", "county" => "COTTLE"],
            ["name" => "CRANE", "county" => "CRANE"],
            ["name" => "OZONA", "county" => "CROCKETT"],
            ["name" => "CROSBYTON", "county" => "CROSBY"],
            ["name" => "LORENZO", "county" => "CROSBY"],
            ["name" => "RALLS", "county" => "CROSBY"],
            ["name" => "VAN HORN", "county" => "CULBERSON"],
            ["name" => "DALHART", "county" => "DALLAM"],
            ["name" => "KERRICK", "county" => "DALLAM"],
            ["name" => "TEXLINE", "county" => "DALLAM"],
            ["name" => "ADDISON", "county" => "DALLAS"],
            ["name" => "BALCH SPRINGS", "county" => "DALLAS"],
            ["name" => "CARROLLTON", "county" => "DALLAS"],
            ["name" => "CEDAR HILL", "county" => "DALLAS"],
            ["name" => "COPPELL", "county" => "DALLAS"],
            ["name" => "DALLAS", "county" => "DALLAS"],
            ["name" => "DESOTO", "county" => "DALLAS"],
            ["name" => "DUNCANVILLE", "county" => "DALLAS"],
            ["name" => "GARLAND", "county" => "DALLAS"],
            ["name" => "GRAND PRAIRIE", "county" => "DALLAS"],
            ["name" => "HUTCHINS", "county" => "DALLAS"],
            ["name" => "IRVING", "county" => "DALLAS"],
            ["name" => "LANCASTER", "county" => "DALLAS"],
            ["name" => "MESQUITE", "county" => "DALLAS"],
            ["name" => "RICHARDSON", "county" => "DALLAS"],
            ["name" => "ROWLETT", "county" => "DALLAS"],
            ["name" => "SACHSE", "county" => "DALLAS"],
            ["name" => "SEAGOVILLE", "county" => "DALLAS"],
            ["name" => "SUNNYVALE", "county" => "DALLAS"],
            ["name" => "WILMER", "county" => "DALLAS"],
            ["name" => "LAMESA", "county" => "DAWSON"],
            ["name" => "WELCH", "county" => "DAWSON"],
            ["name" => "CUERO", "county" => "DE WITT"],
            ["name" => "HOCHHEIM", "county" => "DE WITT"],
            ["name" => "MEYERSVILLE", "county" => "DE WITT"],
            ["name" => "NORDHEIM", "county" => "DE WITT"],
            ["name" => "THOMASTON", "county" => "DE WITT"],
            ["name" => "WESTHOFF", "county" => "DE WITT"],
            ["name" => "YORKTOWN", "county" => "DE WITT"],
            ["name" => "DAWN", "county" => "DEAF SMITH"],
            ["name" => "HEREFORD", "county" => "DEAF SMITH"],
            ["name" => "BEN FRANKLIN", "county" => "DELTA"],
            ["name" => "COOPER", "county" => "DELTA"],
            ["name" => "ENLOE", "county" => "DELTA"],
            ["name" => "KLONDIKE", "county" => "DELTA"],
            ["name" => "LAKE CREEK", "county" => "DELTA"],
            ["name" => "PECAN GAP", "county" => "DELTA"],
            ["name" => "ARGYLE", "county" => "DENTON"],
            ["name" => "AUBREY", "county" => "DENTON"],
            ["name" => "CARROLLTON", "county" => "DENTON"],
            ["name" => "DENTON", "county" => "DENTON"],
            ["name" => "FLOWER MOUND", "county" => "DENTON"],
            ["name" => "FRISCO", "county" => "DENTON"],
            ["name" => "JUSTIN", "county" => "DENTON"],
            ["name" => "KRUM", "county" => "DENTON"],
            ["name" => "LAKE DALLAS", "county" => "DENTON"],
            ["name" => "LEWISVILLE", "county" => "DENTON"],
            ["name" => "LITTLE ELM", "county" => "DENTON"],
            ["name" => "PILOT POINT", "county" => "DENTON"],
            ["name" => "PONDER", "county" => "DENTON"],
            ["name" => "ROANOKE", "county" => "DENTON"],
            ["name" => "SANGER", "county" => "DENTON"],
            ["name" => "THE COLONY", "county" => "DENTON"],
            ["name" => "AFTON", "county" => "DICKENS"],
            ["name" => "DICKENS", "county" => "DICKENS"],
            ["name" => "MCADOO", "county" => "DICKENS"],
            ["name" => "SPUR", "county" => "DICKENS"],
            ["name" => "ASHERTON", "county" => "DIMMIT"],
            ["name" => "BIG WELLS", "county" => "DIMMIT"],
            ["name" => "CARRIZO SPRINGS", "county" => "DIMMIT"],
            ["name" => "CATARINA", "county" => "DIMMIT"],
            ["name" => "CLARENDON", "county" => "DONLEY"],
            ["name" => "HEDLEY", "county" => "DONLEY"],
            ["name" => "LELIA LAKE", "county" => "DONLEY"],
            ["name" => "BENAVIDES", "county" => "DUVAL"],
            ["name" => "CONCEPCION", "county" => "DUVAL"],
            ["name" => "FREER", "county" => "DUVAL"],
            ["name" => "REALITOS", "county" => "DUVAL"],
            ["name" => "SAN DIEGO", "county" => "DUVAL"],
            ["name" => "CARBON", "county" => "EASTLAND"],
            ["name" => "CISCO", "county" => "EASTLAND"],
            ["name" => "DESDEMONA", "county" => "EASTLAND"],
            ["name" => "EASTLAND", "county" => "EASTLAND"],
            ["name" => "GORMAN", "county" => "EASTLAND"],
            ["name" => "OLDEN", "county" => "EASTLAND"],
            ["name" => "RANGER", "county" => "EASTLAND"],
            ["name" => "RISING STAR", "county" => "EASTLAND"],
            ["name" => "GARDENDALE", "county" => "ECTOR"],
            ["name" => "GOLDSMITH", "county" => "ECTOR"],
            ["name" => "NOTREES", "county" => "ECTOR"],
            ["name" => "ODESSA", "county" => "ECTOR"],
            ["name" => "PENWELL", "county" => "ECTOR"],
            ["name" => "BARKSDALE", "county" => "EDWARDS"],
            ["name" => "ROCKSPRINGS", "county" => "EDWARDS"],
            ["name" => "TELEGRAPH", "county" => "EDWARDS"],
            ["name" => "ANTHONY", "county" => "EL PASO"],
            ["name" => "CANUTILLO", "county" => "EL PASO"],
            ["name" => "CLINT", "county" => "EL PASO"],
            ["name" => "EL PASO", "county" => "EL PASO"],
            ["name" => "FABENS", "county" => "EL PASO"],
            ["name" => "FORT BLISS", "county" => "EL PASO"],
            ["name" => "SAN ELIZARIO", "county" => "EL PASO"],
            ["name" => "TORNILLO", "county" => "EL PASO"],
            ["name" => "AVALON", "county" => "ELLIS"],
            ["name" => "BARDWELL", "county" => "ELLIS"],
            ["name" => "ENNIS", "county" => "ELLIS"],
            ["name" => "FERRIS", "county" => "ELLIS"],
            ["name" => "FORRESTON", "county" => "ELLIS"],
            ["name" => "ITALY", "county" => "ELLIS"],
            ["name" => "MAYPEARL", "county" => "ELLIS"],
            ["name" => "MIDLOTHIAN", "county" => "ELLIS"],
            ["name" => "MILFORD", "county" => "ELLIS"],
            ["name" => "PALMER", "county" => "ELLIS"],
            ["name" => "RED OAK", "county" => "ELLIS"],
            ["name" => "WAXAHACHIE", "county" => "ELLIS"],
            ["name" => "BLUFF DALE", "county" => "ERATH"],
            ["name" => "DUBLIN", "county" => "ERATH"],
            ["name" => "LINGLEVILLE", "county" => "ERATH"],
            ["name" => "MORGAN MILL", "county" => "ERATH"],
            ["name" => "STEPHENVILLE", "county" => "ERATH"],
            ["name" => "CHILTON", "county" => "FALLS"],
            ["name" => "LOTT", "county" => "FALLS"],
            ["name" => "MARLIN", "county" => "FALLS"],
            ["name" => "REAGAN", "county" => "FALLS"],
            ["name" => "ROSEBUD", "county" => "FALLS"],
            ["name" => "SATIN", "county" => "FALLS"],
            ["name" => "BAILEY", "county" => "FANNIN"],
            ["name" => "BONHAM", "county" => "FANNIN"],
            ["name" => "DODD CITY", "county" => "FANNIN"],
            ["name" => "ECTOR", "county" => "FANNIN"],
            ["name" => "GOBER", "county" => "FANNIN"],
            ["name" => "HONEY GROVE", "county" => "FANNIN"],
            ["name" => "IVANHOE", "county" => "FANNIN"],
            ["name" => "LADONIA", "county" => "FANNIN"],
            ["name" => "LEONARD", "county" => "FANNIN"],
            ["name" => "RANDOLPH", "county" => "FANNIN"],
            ["name" => "RAVENNA", "county" => "FANNIN"],
            ["name" => "SAVOY", "county" => "FANNIN"],
            ["name" => "TELEPHONE", "county" => "FANNIN"],
            ["name" => "TRENTON", "county" => "FANNIN"],
            ["name" => "WINDOM", "county" => "FANNIN"],
            ["name" => "CARMINE", "county" => "FAYETTE"],
            ["name" => "ELLINGER", "county" => "FAYETTE"],
            ["name" => "FAYETTEVILLE", "county" => "FAYETTE"],
            ["name" => "FLATONIA", "county" => "FAYETTE"],
            ["name" => "LA GRANGE", "county" => "FAYETTE"],
            ["name" => "LEDBETTER", "county" => "FAYETTE"],
            ["name" => "MULDOON", "county" => "FAYETTE"],
            ["name" => "PLUM", "county" => "FAYETTE"],
            ["name" => "ROUND TOP", "county" => "FAYETTE"],
            ["name" => "SCHULENBURG", "county" => "FAYETTE"],
            ["name" => "WARDA", "county" => "FAYETTE"],
            ["name" => "WARRENTON", "county" => "FAYETTE"],
            ["name" => "WEST POINT", "county" => "FAYETTE"],
            ["name" => "MC CAULLEY", "county" => "FISHER"],
            ["name" => "ROBY", "county" => "FISHER"],
            ["name" => "ROTAN", "county" => "FISHER"],
            ["name" => "SYLVESTER", "county" => "FISHER"],
            ["name" => "AIKEN", "county" => "FLOYD"],
            ["name" => "DOUGHERTY", "county" => "FLOYD"],
            ["name" => "FLOYDADA", "county" => "FLOYD"],
            ["name" => "LOCKNEY", "county" => "FLOYD"],
            ["name" => "SOUTH PLAINS", "county" => "FLOYD"],
            ["name" => "BEASLEY", "county" => "FOARD"],
            ["name" => "FRESNO", "county" => "FORT BEND"],
            ["name" => "FULSHEAR", "county" => "FORT BEND"],
            ["name" => "GUY", "county" => "FORT BEND"],
            ["name" => "HOUSTON", "county" => "FORT BEND"],
            ["name" => "KATY", "county" => "FORT BEND"],
            ["name" => "KENDLETON", "county" => "FORT BEND"],
            ["name" => "MISSOURI CITY", "county" => "FORT BEND"],
            ["name" => "NEEDVILLE", "county" => "FORT BEND"],
            ["name" => "ORCHARD", "county" => "FORT BEND"],
            ["name" => "RICHMOND", "county" => "FORT BEND"],
            ["name" => "ROSENBERG", "county" => "FORT BEND"],
            ["name" => "SIMONTON", "county" => "FORT BEND"],
            ["name" => "STAFFORD", "county" => "FORT BEND"],
            ["name" => "SUGAR LAND", "county" => "FORT BEND"],
            ["name" => "THOMPSONS", "county" => "FORT BEND"],
            ["name" => "THOMPSONS", "county" => "FRANKLIN"],
            ["name" => "MOUNT VERNON", "county" => "FRANKLIN"],
            ["name" => "SCROGGINS", "county" => "FRANKLIN"],
            ["name" => "TALCO", "county" => "FRANKLIN"],
            ["name" => "DONIE", "county" => "FREESTONE"],
            ["name" => "FAIRFIELD", "county" => "FREESTONE"],
            ["name" => "KIRVIN", "county" => "FREESTONE"],
            ["name" => "STREETMAN", "county" => "FREESTONE"],
            ["name" => "TEAGUE", "county" => "FREESTONE"],
            ["name" => "WORTHAM", "county" => "FREESTONE"],
            ["name" => "BIGFOOT", "county" => "FRIO"],
            ["name" => "DILLEY", "county" => "FRIO"],
            ["name" => "MOORE", "county" => "FRIO"],
            ["name" => "PEARSALL", "county" => "FRIO"],
            ["name" => "LOOP", "county" => "GAINES"],
            ["name" => "SEAGRAVES", "county" => "GAINES"],
            ["name" => "SEMINOLE", "county" => "GAINES"],
            ["name" => "BACLIFF", "county" => "GALVESTON"],
            ["name" => "DICKINSON", "county" => "GALVESTON"],
            ["name" => "FRIENDSWOOD", "county" => "GALVESTON"],
            ["name" => "GALVESTON", "county" => "GALVESTON"],
            ["name" => "GILCHRIST", "county" => "GALVESTON"],
            ["name" => "HIGH ISLAND", "county" => "GALVESTON"],
            ["name" => "HITCHCOCK", "county" => "GALVESTON"],
            ["name" => "KEMAH", "county" => "GALVESTON"],
            ["name" => "LA MARQUE", "county" => "GALVESTON"],
            ["name" => "LEAGUE CITY", "county" => "GALVESTON"],
            ["name" => "PORT BOLIVAR", "county" => "GALVESTON"],
            ["name" => "SANTA FE", "county" => "GALVESTON"],
            ["name" => "TEXAS CITY", "county" => "GALVESTON"],
            ["name" => "JUSTICEBURG", "county" => "GARZA"],
            ["name" => "POST", "county" => "GARZA"],
            ["name" => "DOSS", "county" => "GILLESPIE"],
            ["name" => "FREDERICKSBURG", "county" => "GILLESPIE"],
            ["name" => "HARPER", "county" => "GILLESPIE"],
            ["name" => "STONEWALL", "county" => "GILLESPIE"],
            ["name" => "WILLOW CITY", "county" => "GILLESPIE"],
            ["name" => "GARDEN CITY", "county" => "GLASSCOCK"],
            ["name" => "BERCLAIR", "county" => "GOLIAD"],
            ["name" => "FANNIN", "county" => "GOLIAD"],
            ["name" => "GOLIAD", "county" => "GOLIAD"],
            ["name" => "WEESATCHE", "county" => "GOLIAD"],
            ["name" => "BELMONT", "county" => "GONZALES"],
            ["name" => "COST", "county" => "GONZALES"],
            ["name" => "GONZALES", "county" => "GONZALES"],
            ["name" => "HARWOOD", "county" => "GONZALES"],
            ["name" => "LEESVILLE", "county" => "GONZALES"],
            ["name" => "NIXON	", "county" => "GONZALES"],
            ["name" => "OTTINE", "county" => "GONZALES"],
            ["name" => "SMILEY", "county" => "GONZALES"],
            ["name" => "WAELDER", "county" => "GONZALES"],
            ["name" => "WRIGHTSBORO", "county" => "GONZALES"],
            ["name" => "ALANREED", "county" => "GRAY"],
            ["name" => "LEFORS", "county" => "GRAY"],
            ["name" => "MCLEAN", "county" => "GRAY"],
            ["name" => "PAMPA", "county" => "GRAY"],
            ["name" => "BELLS", "county" => "GRAYSON"],
            ["name" => "COLLINSVILLE", "county" => "GRAYSON"],
            ["name" => "DENISON", "county" => "GRAYSON"],
            ["name" => "GORDONVILLE", "county" => "GRAYSON"],
            ["name" => "GUNTER", "county" => "GRAYSON"],
            ["name" => "HOWE", "county" => "GRAYSON"],
            ["name" => "POTTSBORO", "county" => "GRAYSON"],
            ["name" => "SADLER", "county" => "GRAYSON"],
            ["name" => "SHERMAN", "county" => "GRAYSON"],
            ["name" => "SOUTHMAYD", "county" => "GRAYSON"],
            ["name" => "TIOGA", "county" => "GRAYSON"],
            ["name" => "TOM BEAN", "county" => "GRAYSON"],
            ["name" => "VAN ALSTYNE", "county" => "GRAYSON"],
            ["name" => "WHITESBORO", "county" => "GRAYSON"],
            ["name" => "WHITEWRIGHT", "county" => "GRAYSON"],
            ["name" => "EASTON", "county" => "GREGG"],
            ["name" => "GLADEWATER", "county" => "GREGG"],
            ["name" => "JUDSON", "county" => "GREGG"],
            ["name" => "KILGORE", "county" => "GREGG"],
            ["name" => "LONGVIEW", "county" => "GREGG"],
            ["name" => "WHITE OAK", "county" => "GREGG"],
            ["name" => "ANDERSON", "county" => "GRIMES"],
            ["name" => "BEDIAS", "county" => "GRIMES"],
            ["name" => "IOLA", "county" => "GRIMES"],
            ["name" => "NAVASOTA", "county" => "GRIMES"],
            ["name" => "PLANTERSVILLE", "county" => "GRIMES"],
            ["name" => "RICHARDS", "county" => "GRIMES"],
            ["name" => "ROANS PRAIRIE", "county" => "GRIMES"],
            ["name" => "SHIRO", "county" => "GRIMES"],
            ["name" => "CIBOLO", "county" => "GUADALUPE"],
            ["name" => "GERONIMO", "county" => "GUADALUPE"],
            ["name" => "KINGSBURY", "county" => "GUADALUPE"],
            ["name" => "MARION", "county" => "GUADALUPE"],
            ["name" => "MC QUEENEY", "county" => "GUADALUPE"],
            ["name" => "SCHERTZ", "county" => "GUADALUPE"],
            ["name" => "SEGUIN", "county" => "GUADALUPE"],
            ["name" => "STAPLES", "county" => "GUADALUPE"],
            ["name" => "ABERNATHY", "county" => "HALE"],
            ["name" => "COTTON CENTER", "county" => "HALE"],
            ["name" => "EDMONSON", "county" => "HALE"],
            ["name" => "HALE CENTER", "county" => "HALE"],
            ["name" => "PETERSBURG", "county" => "HALE"],
            ["name" => "PLAINVIEW", "county" => "HALE"],
            ["name" => "ESTELLINE", "county" => "HALL"],
            ["name" => "LAKEVIEW", "county" => "HALL"],
            ["name" => "MEMPHIS", "county" => "HALL"],
            ["name" => "TURKEY", "county" => "HALL"],
            ["name" => "CARLTON", "county" => "HAMILTON"],
            ["name" => "HAMILTON", "county" => "HAMILTON"],
            ["name" => "HICO", "county" => "HAMILTON"],
            ["name" => "POTTSVILLE", "county" => "HAMILTON"],
            ["name" => "GRUVER", "county" => "HANSFORD"],
            ["name" => "MORSE", "county" => "HANSFORD"],
            ["name" => "SPEARMAN", "county" => "HANSFORD"],
            ["name" => "CHILLICOTHE", "county" => "HARDEMAN"],
            ["name" => "QUANAH", "county" => "HARDEMAN"],
            ["name" => "BATSON", "county" => "HARDIN"],
            ["name" => "KOUNTZE", "county" => "HARDIN"],
            ["name" => "LUMBERTON", "county" => "HARDIN"],
            ["name" => "SARATOGA", "county" => "HARDIN"],
            ["name" => "SILSBEE", "county" => "HARDIN"],
            ["name" => "SOUR LAKE", "county" => "HARDIN"],
            ["name" => "THICKET", "county" => "HARDIN"],
            ["name" => "VILLAGE MILLS", "county" => "HARDIN"],
            ["name" => "VOTAW", "county" => "HARDIN"],
            ["name" => "ALIEF", "county" => "HARRIS"],
            ["name" => "BARKER", "county" => "HARRIS"],
            ["name" => "BAYTOWN", "county" => "HARRIS"],
            ["name" => "BELLAIRE", "county" => "HARRIS"],
            ["name" => "CHANNELVIEW", "county" => "HARRIS"],
            ["name" => "CROSBY", "county" => "HARRIS"],
            ["name" => "CYPRESS", "county" => "HARRIS"],
            ["name" => "DEER PARK", "county" => "HARRIS"],
            ["name" => "GALENA PARK", "county" => "HARRIS"],
            ["name" => "HIGHLANDS", "county" => "HARRIS"],
            ["name" => "HOCKLEY", "county" => "HARRIS"],
            ["name" => "HOUSTON", "county" => "HARRIS"],
            ["name" => "HUFFMAN", "county" => "HARRIS"],
            ["name" => "HUFSMITH", "county" => "HARRIS"],
            ["name" => "HUMBLE", "county" => "HARRIS"],
            ["name" => "KATY", "county" => "HARRIS"],
            ["name" => "KINGWOOD", "county" => "HARRIS"],
            ["name" => "LA PORTE", "county" => "HARRIS"],
            ["name" => "NORTH HOUSTON", "county" => "HARRIS"],
            ["name" => "PASADENA", "county" => "HARRIS"],
            ["name" => "SEABROOK", "county" => "HARRIS"],
            ["name" => "SOUTH HOUSTON", "county" => "HARRIS"],
            ["name" => "SPRING", "county" => "HARRIS"],
            ["name" => "SPRING", "county" => "HARRIS"],
            ["name" => "WALLER", "county" => "HARRIS"],
            ["name" => "WEBSTER", "county" => "HARRIS"],
            ["name" => "ELYSIAN FIELDS", "county" => "HARRISON"],
            ["name" => "HALLSVILLE", "county" => "HARRISON"],
            ["name" => "HARLETON", "county" => "HARRISON"],
            ["name" => "JONESVILLE", "county" => "HARRISON"],
            ["name" => "KARNACK", "county" => "HARRISON"],
            ["name" => "MARSHALL", "county" => "HARRISON"],
            ["name" => "SCOTTSVILLE", "county" => "HARRISON"],
            ["name" => "WASKOM", "county" => "HARRISON"],
            ["name" => "WOODLAWN", "county" => "HARRISON"],
            ["name" => "CHANNING", "county" => "HARTLEY"],
            ["name" => "HARTLEY", "county" => "HARTLEY"],
            ["name" => "HASKELL", "county" => "HASKELL"],
            ["name" => "O BRIEN", "county" => "HASKELL"],
            ["name" => "ROCHESTER", "county" => "HASKELL"],
            ["name" => "RULE", "county" => "HASKELL"],
            ["name" => "WEINERT", "county" => "HASKELL"],
            ["name" => "AUSTIN", "county" => "HAYS"],
            ["name" => "BUDA", "county" => "HAYS"],
            ["name" => "DRIFTWOOD", "county" => "HAYS"],
            ["name" => "DRIPPING SPRINGS", "county" => "HAYS"],
            ["name" => "KYLE", "county" => "HAYS"],
            ["name" => "SAN MARCOS", "county" => "HAYS"],
            ["name" => "WIMBERLEY", "county" => "HAYS"],
            ["name" => "CANADIAN", "county" => "HEMPHILL"],
            ["name" => "ATHENS", "county" => "HENDERSON"],
            ["name" => "BROWNSBORO", "county" => "HENDERSON"],
            ["name" => "CHANDLER", "county" => "HENDERSON"],
            ["name" => "EUSTACE", "county" => "HENDERSON"],
            ["name" => "LARUE", "county" => "HENDERSON"],
            ["name" => "MABANK", "county" => "HENDERSON"],
            ["name" => "MALAKOFF", "county" => "HENDERSON"],
            ["name" => "MURCHISON", "county" => "HENDERSON"],
            ["name" => "POYNOR", "county" => "HENDERSON"],
            ["name" => "TRINIDAD", "county" => "HENDERSON"],
            ["name" => "ALAMO", "county" => "HIDALGO"],
            ["name" => "DONNA", "county" => "HIDALGO"],
            ["name" => "EDCOUCH", "county" => "HIDALGO"],
            ["name" => "EDINBURG", "county" => "HIDALGO"],
            ["name" => "ELSA", "county" => "HIDALGO"],
            ["name" => "HARGILL", "county" => "HIDALGO"],
            ["name" => "HIDALGO", "county" => "HIDALGO"],
            ["name" => "LA BLANCA", "county" => "HIDALGO"],
            ["name" => "LA JOYA", "county" => "HIDALGO"],
            ["name" => "LA VILLA", "county" => "HIDALGO"],
            ["name" => "LINN", "county" => "HIDALGO"],
            ["name" => "LOS EBANOS", "county" => "HIDALGO"],
            ["name" => "MCALLEN", "county" => "HIDALGO"],
            ["name" => "MERCEDES", "county" => "HIDALGO"],
            ["name" => "MISSION", "county" => "HIDALGO"],
            ["name" => "PENITAS", "county" => "HIDALGO"],
            ["name" => "PHARR", "county" => "HIDALGO"],
            ["name" => "PROGRESO", "county" => "HIDALGO"],
            ["name" => "SAN JUAN", "county" => "HIDALGO"],
            ["name" => "SULLIVAN CITY", "county" => "HIDALGO"],
            ["name" => "WESLACO", "county" => "HIDALGO"],
            ["name" => "ABBOTT", "county" => "HILL"],
            ["name" => "AQUILLA", "county" => "HILL"],
            ["name" => "BLUM", "county" => "HILL"],
            ["name" => "BRANDON", "county" => "HILL"],
            ["name" => "BYNUM", "county" => "HILL"],
            ["name" => "COVINGTON", "county" => "HILL"],
            ["name" => "HILLSBORO", "county" => "HILL"],
            ["name" => "HUBBARD", "county" => "HILL"],
            ["name" => "IRENE", "county" => "HILL"],
            ["name" => "ITASCA", "county" => "HILL"],
            ["name" => "MALONE", "county" => "HILL"],
            ["name" => "MERTENS", "county" => "HILL"],
            ["name" => "MOUNT CALM", "county" => "HILL"],
            ["name" => "PENELOPE", "county" => "HILL"],
            ["name" => "WHITNEY", "county" => "HILL"],
            ["name" => "ANTON", "county" => "HOCKLEY"],
            ["name" => "LEVELLAND", "county" => "HOCKLEY"],
            ["name" => "PEP", "county" => "HOCKLEY"],
            ["name" => "ROPESVILLE", "county" => "HOCKLEY"],
            ["name" => "SMYER", "county" => "HOCKLEY"],
            ["name" => "SUNDOWN", "county" => "HOCKLEY"],
            ["name" => "WHITHARRAL", "county" => "HOCKLEY"],
            ["name" => "CRESSON", "county" => "HOOD"],
            ["name" => "GRANBURY", "county" => "HOOD"],
            ["name" => "LIPAN", "county" => "HOOD"],
            ["name" => "PALUXY", "county" => "HOOD"],
            ["name" => "TOLAR", "county" => "HOOD"],
            ["name" => "BRASHEAR", "county" => "HOPKINS"],
            ["name" => "COMO", "county" => "HOPKINS"],
            ["name" => "CUMBY", "county" => "HOPKINS"],
            ["name" => "DIKE", "county" => "HOPKINS"],
            ["name" => "PICKTON", "county" => "HOPKINS"],
            ["name" => "SALTILLO", "county" => "HOPKINS"],
            ["name" => "SULPHUR BLUFF", "county" => "HOPKINS"],
            ["name" => "SULPHUR SPRINGS", "county" => "HOPKINS"],
            ["name" => "CROCKETT", "county" => "HOUSTON"],
            ["name" => "GRAPELAND", "county" => "HOUSTON"],
            ["name" => "KENNARD", "county" => "HOUSTON"],
            ["name" => "LATEXO", "county" => "HOUSTON"],
            ["name" => "LOVELADY", "county" => "HOUSTON"],
            ["name" => "RATCLIFF", "county" => "HOUSTON"],
            ["name" => "BIG SPRING", "county" => "HOWARD"],
            ["name" => "COAHOMA", "county" => "HOWARD"],
            ["name" => "FORSAN", "county" => "HOWARD"],
            ["name" => "KNOTT", "county" => "HOWARD"],
            ["name" => "DELL CITY", "county" => "HUDSPETH"],
            ["name" => "FORT HANCOCK", "county" => "HUDSPETH"],
            ["name" => "SALT FLAT", "county" => "HUDSPETH"],
            ["name" => "SIERRA BLANCA", "county" => "HUDSPETH"],
            ["name" => "CADDO MILLS", "county" => "HUNT"],
            ["name" => "CAMPBELL", "county" => "HUNT"],
            ["name" => "CELESTE", "county" => "HUNT"],
            ["name" => "COMMERCE", "county" => "HUNT"],
            ["name" => "GREENVILLE", "county" => "HUNT"],
            ["name" => "LONE OAK", "county" => "HUNT"],
            ["name" => "MERIT", "county" => "HUNT"],
            ["name" => "QUINLAN", "county" => "HUNT"],
            ["name" => "WOLFE CITY", "county" => "HUNT"],
            ["name" => "BORGER", "county" => "HUTCHINSON"],
            ["name" => "FRITCH", "county" => "HUTCHINSON"],
            ["name" => "SANFORD", "county" => "HUTCHINSON"],
            ["name" => "STINNETT", "county" => "HUTCHINSON"],
            ["name" => "BARNHART", "county" => "IRION"],
            ["name" => "MERTZON", "county" => "IRION"],
            ["name" => "BRYSON", "county" => "JACK"],
            ["name" => "JACKSBORO", "county" => "JACK"],
            ["name" => "JERMYN", "county" => "JACK"],
            ["name" => "PERRIN", "county" => "JACK"],
            ["name" => "EDNA", "county" => "JACKSON"],
            ["name" => "FRANCITAS", "county" => "JACKSON"],
            ["name" => "GANADO", "county" => "JACKSON"],
            ["name" => "LA SALLE", "county" => "JACKSON"],
            ["name" => "LA WARD", "county" => "JACKSON"],
            ["name" => "LOLITA", "county" => "JACKSON"],
            ["name" => "VANDERBILT", "county" => "JACKSON"],
            ["name" => "BROOKELAND", "county" => "JASPER"],
            ["name" => "BUNA", "county" => "JASPER"],
            ["name" => "EVADALE", "county" => "JASPER"],
            ["name" => "JASPER", "county" => "JASPER"],
            ["name" => "KIRBYVILLE", "county" => "JASPER"],
            ["name" => "FORT DAVIS", "county" => "JEFF DAVIS"],
            ["name" => "BEAUMONT", "county" => "JEFFERSON"],
            ["name" => "CHINA", "county" => "JEFFERSON"],
            ["name" => "GROVES", "county" => "JEFFERSON"],
            ["name" => "HAMSHIRE", "county" => "JEFFERSON"],
            ["name" => "NEDERLAND", "county" => "JEFFERSON"],
            ["name" => "NOME", "county" => "JEFFERSON"],
            ["name" => "PORT ARTHUR", "county" => "JEFFERSON"],
            ["name" => "PORT NECHES", "county" => "JEFFERSON"],
            ["name" => "SABINE PASS", "county" => "JEFFERSON"],
            ["name" => "GUERRA", "county" => "JIM HOGG"],
            ["name" => "HEBBRONVILLE", "county" => "JIM HOGG"],
            ["name" => "ALICE", "county" => "JIM WELLS"],
            ["name" => "BEN BOLT", "county" => "JIM WELLS"],
            ["name" => "ORANGE GROVE", "county" => "JIM WELLS"],
            ["name" => "PREMONT", "county" => "JIM WELLS"],
            ["name" => "SANDIA", "county" => "JIM WELLS"],
            ["name" => "ALVARADO", "county" => "JOHNSON"],
            ["name" => "BURLESON", "county" => "JOHNSON"],
            ["name" => "CLEBURNE", "county" => "JOHNSON"],
            ["name" => "GODLEY", "county" => "JOHNSON"],
            ["name" => "GRANDVIEW", "county" => "JOHNSON"],
            ["name" => "JOSHUA", "county" => "JOHNSON"],
            ["name" => "KEENE", "county" => "JOHNSON"],
            ["name" => "LILLIAN", "county" => "JOHNSON"],
            ["name" => "RIO VISTA", "county" => "JOHNSON"],
            ["name" => "VENUS", "county" => "JOHNSON"],
            ["name" => "ANSON", "county" => "JONES"],
            ["name" => "AVOCA", "county" => "JONES"],
            ["name" => "HAWLEY", "county" => "JONES"],
            ["name" => "LUEDERS", "county" => "JONES"],
            ["name" => "STAMFORD", "county" => "JONES"],
            ["name" => "HAMLIN", "county" => "JONES"],
            ["name" => "ECLETO", "county" => "KARNES"],
            ["name" => "FALLS CITY", "county" => "KARNES"],
            ["name" => "GILLETT", "county" => "KARNES"],
            ["name" => "HOBSON", "county" => "KARNES"],
            ["name" => "KARNES CITY", "county" => "KARNES"],
            ["name" => "KENEDY", "county" => "KARNES"],
            ["name" => "PANNA MARIA", "county" => "KARNES"],
            ["name" => "RUNGE", "county" => "KARNES"],
            ["name" => "CRANDALL", "county" => "KAUFMAN"],
            ["name" => "ELMO", "county" => "KAUFMAN"],
            ["name" => "FORNEY", "county" => "KAUFMAN"],
            ["name" => "KAUFMAN", "county" => "KAUFMAN"],
            ["name" => "KEMP", "county" => "KAUFMAN"],
            ["name" => "MABANK", "county" => "KAUFMAN"],
            ["name" => "ROSSER", "county" => "KAUFMAN"],
            ["name" => "SCURRY", "county" => "KAUFMAN"],
            ["name" => "TERRELL", "county" => "KAUFMAN"],
            ["name" => "BERGHEIM", "county" => "KENDALL"],
            ["name" => "BOERNE", "county" => "KENDALL"],
            ["name" => "COMFORT", "county" => "KENDALL"],
            ["name" => "KENDALIA", "county" => "KENDALL"],
            ["name" => "WARING", "county" => "KENDALL"],
            ["name" => "ARMSTRONG", "county" => "KENEDY"],
            ["name" => "SARITA", "county" => "KENEDY"],
            ["name" => "GIRARD", "county" => "KENT"],
            ["name" => "JAYTON", "county" => "KENT"],
            ["name" => "CENTER POINT", "county" => "KERR"],
            ["name" => "HUNT", "county" => "KERR"],
            ["name" => "INGRAM", "county" => "KERR"],
            ["name" => "KERRVILLE", "county" => "KERR"],
            ["name" => "MOUNTAIN HOME", "county" => "KERR"],
            ["name" => "JUNCTION", "county" => "KIMBLE"],
            ["name" => "LONDON", "county" => "KIMBLE"],
            ["name" => "ROOSEVELT", "county" => "KIMBLE"],
            ["name" => "GUTHRIE", "county" => "KING"],
            ["name" => "BRACKETTVILLE", "county" => "KINNEY"],
            ["name" => "KINGSVILLE", "county" => "KLEBERG"],
            ["name" => "RIVIERA", "county" => "KLEBERG"],
            ["name" => "BENJAMIN", "county" => "KNOX"],
            ["name" => "GOREE", "county" => "KNOX"],
            ["name" => "KNOX CITY", "county" => "KNOX"],
            ["name" => "MUNDAY", "county" => "KNOX"],
            ["name" => "ARTESIA WELLS", "county" => "LA SALLE"],
            ["name" => "COTULLA", "county" => "LA SALLE"],
            ["name" => "ENCINAL", "county" => "LA SALLE"],
            ["name" => "FOWLERTON", "county" => "LA SALLE"],
            ["name" => "ARTHUR CITY", "county" => "LAMAR"],
            ["name" => "BLOSSOM", "county" => "LAMAR"],
            ["name" => "BROOKSTON", "county" => "LAMAR"],
            ["name" => "CHICOTA", "county" => "LAMAR"],
            ["name" => "CUNNINGHAM", "county" => "LAMAR"],
            ["name" => "DEPORT", "county" => "LAMAR"],
            ["name" => "PARIS", "county" => "LAMAR"],
            ["name" => "PATTONVILLE", "county" => "LAMAR"],
            ["name" => "PETTY", "county" => "LAMAR"],
            ["name" => "POWDERLY", "county" => "LAMAR"],
            ["name" => "ROXTON", "county" => "LAMAR"],
            ["name" => "SUMNER", "county" => "LAMAR"],
            ["name" => "AMHERST", "county" => "LAMB"],
            ["name" => "EARTH", "county" => "LAMB"],
            ["name" => "FIELDTON", "county" => "LAMB"],
            ["name" => "LITTLEFIELD", "county" => "LAMB"],
            ["name" => "OLTON", "county" => "LAMB"],
            ["name" => "SPADE", "county" => "LAMB"],
            ["name" => "SPRINGLAKE", "county" => "LAMB"],
            ["name" => "SUDAN", "county" => "LAMB"],
            ["name" => "KEMPNER", "county" => "LAMPASAS"],
            ["name" => "LAMPASAS", "county" => "LAMPASAS"],
            ["name" => "LOMETA", "county" => "LAMPASAS"],
            ["name" => "HALLETTSVILLE", "county" => "LAVACA"],
            ["name" => "MOULTON", "county" => "LAVACA"],
            ["name" => "SHINER", "county" => "LAVACA"],
            ["name" => "SUBLIME", "county" => "LAVACA"],
            ["name" => "SWEET HOME", "county" => "LAVACA"],
            ["name" => "YOAKUM", "county" => "LAVACA"],
            ["name" => "DIME BOX", "county" => "LEE"],
            ["name" => "GIDDINGS", "county" => "LEE"],
            ["name" => "LEXINGTON", "county" => "LEE"],
            ["name" => "LINCOLN", "county" => "LEE"],
            ["name" => "BUFFALO", "county" => "LEON"],
            ["name" => "CENTERVILLE", "county" => "LEON"],
            ["name" => "CONCORD", "county" => "LEON"],
            ["name" => "FLYNN", "county" => "LEON"],
            ["name" => "JEWETT", "county" => "LEON"],
            ["name" => "LEONA", "county" => "LEON"],
            ["name" => "MARQUEZ", "county" => "LEON"],
            ["name" => "NORMANGEE", "county" => "LEON"],
            ["name" => "OAKWOOD", "county" => "LEON"],
            ["name" => "CLEVELAND", "county" => "LIBERTY"],
            ["name" => "DAISETTA", "county" => "LIBERTY"],
            ["name" => "DAYTON", "county" => "LIBERTY"],
            ["name" => "DEVERS", "county" => "LIBERTY"],
            ["name" => "HARDIN", "county" => "LIBERTY"],
            ["name" => "HULL", "county" => "LIBERTY"],
            ["name" => "LIBERTY", "county" => "LIBERTY"],
            ["name" => "RAYWOOD", "county" => "LIBERTY"],
            ["name" => "ROMAYOR", "county" => "LIBERTY"],
            ["name" => "RYE", "county" => "LIBERTY"],
            ["name" => "COOLIDGE", "county" => "LIMESTONE"],
            ["name" => "GROESBECK", "county" => "LIMESTONE"],
            ["name" => "KOSSE", "county" => "LIMESTONE"],
            ["name" => "MEXIA", "county" => "LIMESTONE"],
            ["name" => "PRAIRIE HILL", "county" => "LIMESTONE"],
            ["name" => "TEHUACANA", "county" => "LIMESTONE"],
            ["name" => "THORNTON", "county" => "LIMESTONE"],
            ["name" => "BOOKER", "county" => "LIPSCOMB"],
            ["name" => "DARROUZETT", "county" => "LIPSCOMB"],
            ["name" => "FOLLETT", "county" => "LIPSCOMB"],
            ["name" => "HIGGINS", "county" => "LIPSCOMB"],
            ["name" => "LIPSCOMB", "county" => "LIPSCOMB"],
            ["name" => "DINERO", "county" => "LIVE OAK"],
            ["name" => "GEORGE WEST", "county" => "LIVE OAK"],
            ["name" => "OAKVILLE", "county" => "LIVE OAK"],
            ["name" => "THREE RIVERS", "county" => "LIVE OAK"],
            ["name" => "WHITSETT", "county" => "LIVE OAK"],
            ["name" => "BLUFFTON", "county" => "LLANO"],
            ["name" => "BUCHANAN DAM", "county" => "LLANO"],
            ["name" => "CASTELL", "county" => "LLANO"],
            ["name" => "HORSESHOE BAY", "county" => "LLANO"],
            ["name" => "KINGSLAND", "county" => "LLANO"],
            ["name" => "LLANO", "county" => "LLANO"],
            ["name" => "TOW", "county" => "LLANO"],
            ["name" => "VALLEY SPRING", "county" => "LLANO"],
            ["name" => "MENTONE", "county" => "LOVING"],
            ["name" => "IDALOU", "county" => "LUBBOCK"],
            ["name" => "LUBBOCK", "county" => "LUBBOCK"],
            ["name" => "NEW DEAL", "county" => "LUBBOCK"],
            ["name" => "RANSOM CANYON", "county" => "LUBBOCK"],
            ["name" => "SHALLOWATER", "county" => "LUBBOCK"],
            ["name" => "SLATON", "county" => "LUBBOCK"],
            ["name" => "WOLFFORTH", "county" => "LUBBOCK"],
            ["name" => "NEW HOME", "county" => "LYNN"],
            ["name" => "ODONNELL", "county" => "LYNN"],
            ["name" => "TAHOKA", "county" => "LYNN"],
            ["name" => "WILSON", "county" => "LYNN"],
            ["name" => "MADISONVILLE", "county" => "MADISON"],
            ["name" => "MIDWAY", "county" => "MADISON"],
            ["name" => "NORTH ZULCH", "county" => "MADISON"],
            ["name" => "JEFFERSON", "county" => "MARION"],
            ["name" => "LODI", "county" => "MARION"],
            ["name" => "ACKERLY", "county" => "MARTIN"],
            ["name" => "ALENORAH", "county" => "MARTIN"],
            ["name" => "STANTON", "county" => "MARTIN"],
            ["name" => "TARZAN", "county" => "MARTIN"],
            ["name" => "ART", "county" => "MASON"],
            ["name" => "FREDONIA", "county" => "MASON"],
            ["name" => "MASON", "county" => "MASON"],
            ["name" => "PONTOTOC", "county" => "MASON"],
            ["name" => "BAY CITY", "county" => "MATAGORDA"],
            ["name" => "BLESSING", "county" => "MATAGORDA"],
            ["name" => "CEDAR LANE", "county" => "MATAGORDA"],
            ["name" => "COLLEGEPORT", "county" => "MATAGORDA"],
            ["name" => "ELMATON", "county" => "MATAGORDA"],
            ["name" => "MARKHAM", "county" => "MATAGORDA"],
            ["name" => "MATAGORDA", "county" => "MATAGORDA"],
            ["name" => "MIDFIELD", "county" => "MATAGORDA"],
            ["name" => "PALACIOS", "county" => "MATAGORDA"],
            ["name" => "PLEDGER", "county" => "MATAGORDA"],
            ["name" => "VAN VLECK", "county" => "MATAGORDA"],
            ["name" => "WADSWORTH", "county" => "MATAGORDA"],
            ["name" => "EAGLE PASS", "county" => "MAVERICK"],
            ["name" => "EL INDIO", "county" => "MAVERICK"],
            ["name" => "QUEMADO", "county" => "MAVERICK"],
            ["name" => "BRADY", "county" => "MCCULLOCH"],
            ["name" => "DOOLE", "county" => "MCCULLOCH"],
            ["name" => "LOHN", "county" => "MCCULLOCH"],
            ["name" => "MELVIN", "county" => "MCCULLOCH"],
            ["name" => "ROCHELLE", "county" => "MCCULLOCH"],
            ["name" => "VOCA", "county" => "MCCULLOCH"],
            ["name" => "AXTELL", "county" => "MCLENNAN"],
            ["name" => "BRUCEVILLE", "county" => "MCLENNAN"],
            ["name" => "CHINA SPRING", "county" => "MCLENNAN"],
            ["name" => "CRAWFORD", "county" => "MCLENNAN"],
            ["name" => "EDDY", "county" => "MCLENNAN"],
            ["name" => "ELM MOTT", "county" => "MCLENNAN"],
            ["name" => "HEWITT", "county" => "MCLENNAN"],
            ["name" => "LEROY", "county" => "MCLENNAN"],
            ["name" => "LORENA", "county" => "MCLENNAN"],
            ["name" => "MART", "county" => "MCLENNAN"],
            ["name" => "MC", "county" => "MCLENNAN"],
            ["name" => "MOODY", "county" => "MCLENNAN"],
            ["name" => "RIESEL", "county" => "MCLENNAN"],
            ["name" => "ROSS", "county" => "MCLENNAN"],
            ["name" => "WACO", "county" => "MCLENNAN"],
            ["name" => "WEST", "county" => "MCLENNAN"],
            ["name" => "WOODWAY", "county" => "MCLENNAN"],
            ["name" => "CALLIHAM", "county" => "MCMULLEN"],
            ["name" => "TILDEN", "county" => "MCMULLEN"],
            ["name" => "CASTROVILLE", "county" => "MEDINA"],
            ["name" => "D HANIS", "county" => "MEDINA"],
            ["name" => "DEVINE", "county" => "MEDINA"],
            ["name" => "HONDO", "county" => "MEDINA"],
            ["name" => "LA COSTE", "county" => "MEDINA"],
            ["name" => "MICO", "county" => "MEDINA"],
            ["name" => "NATALIA", "county" => "MEDINA"],
            ["name" => "RIO MEDINA", "county" => "MEDINA"],
            ["name" => "YANCEY", "county" => "MEDINA"],
            ["name" => "FORT MC KAVETT", "county" => "MENARD"],
            ["name" => "HEXT", "county" => "MENARD"],
            ["name" => "MENARD", "county" => "MENARD"],
            ["name" => "MIDLAND", "county" => "MIDLAND"],
            ["name" => "BUCKHOLTS", "county" => "MILAM"],
            ["name" => "BURLINGTON", "county" => "MILAM"],
            ["name" => "CAMERON", "county" => "MILAM"],
            ["name" => "DAVILLA", "county" => "MILAM"],
            ["name" => "GAUSE", "county" => "MILAM"],
            ["name" => "MILANO", "county" => "MILAM"],
            ["name" => "ROCKDALE", "county" => "MILAM"],
            ["name" => "THORNDALE", "county" => "MILAM"],
            ["name" => "GOLDTHWAITE", "county" => "MILLS"],
            ["name" => "MULLIN", "county" => "MILLS"],
            ["name" => "PRIDDY", "county" => "MILLS"],
            ["name" => "STAR", "county" => "MILLS"],
            ["name" => "COLORADO", "county" => "MITCHELL"],
            ["name" => "LORAINE", "county" => "MITCHELL"],
            ["name" => "WESTBROOK", "county" => "MITCHELL"],
            ["name" => "BOWIE", "county" => "MONTAGUE"],
            ["name" => "FORESTBURG", "county" => "MONTAGUE"],
            ["name" => "MONTAGUE", "county" => "MONTAGUE"],
            ["name" => "NOCONA", "county" => "MONTAGUE"],
            ["name" => "RINGGOLD", "county" => "MONTAGUE"],
            ["name" => "SAINT JO	", "county" => "MONTAGUE"],
            ["name" => "SUNSET", "county" => "MONTAGUE"],
            ["name" => "CONROE", "county" => "MONTGOMERY"],
            ["name" => "DOBBIN", "county" => "MONTGOMERY"],
            ["name" => "MAGNOLIA", "county" => "MONTGOMERY"],
            ["name" => "MONTGOMERY", "county" => "MONTGOMERY"],
            ["name" => "NEW CANEY", "county" => "MONTGOMERY"],
            ["name" => "PINEHURST", "county" => "MONTGOMERY"],
            ["name" => "PORTER", "county" => "MONTGOMERY"],
            ["name" => "SPLENDORA", "county" => "MONTGOMERY"],
            ["name" => "SPRING", "county" => "county"],
            ["name" => "WILLIS", "county" => "MONTGOMERY"],
            ["name" => "CACTUS", "county" => "MOORE"],
            ["name" => "DUMAS", "county" => "MOORE"],
            ["name" => "MASTERSON", "county" => "MOORE"],
            ["name" => "SUNRAY", "county" => "MOORE"],
            ["name" => "CASON", "county" => "MORRIS"],
            ["name" => "DAINGERFIELD", "county" => "MORRIS"],
            ["name" => "LONE STAR	", "county" => "MORRIS"],
            ["name" => "NAPLES", "county" => "MORRIS"],
            ["name" => "OMAHA", "county" => "MORRIS"],
            ["name" => "FLOMOT", "county" => "MOTLEY"],
            ["name" => "MATADOR", "county" => "MOTLEY"],
            ["name" => "ROARING SPRINGS", "county" => "MOTLEY"],
            ["name" => "CHIRENO", "county" => "NACOGDOCHES"],
            ["name" => "CUSHING", "county" => "NACOGDOCHES"],
            ["name" => "DOUGLASS", "county" => "NACOGDOCHES"],
            ["name" => "ETOILE", "county" => "NACOGDOCHES"],
            ["name" => "GARRISON", "county" => "NACOGDOCHES"],
            ["name" => "MARTINSVILLE", "county" => "NACOGDOCHES"],
            ["name" => "NACOGDOCHES", "county" => "NACOGDOCHES"],
            ["name" => "SACUL", "county" => "NACOGDOCHES"],
            ["name" => "WODEN", "county" => "NACOGDOCHES"],
            ["name" => "BARRY", "county" => "NAVARRO"],
            ["name" => "BLOOMING", "county" => "NAVARRO"],
            ["name" => "CHATFIELD", "county" => "NAVARRO"],
            ["name" => "CORSICANA", "county" => "NAVARRO"],
            ["name" => "DAWSON", "county" => "NAVARRO"],
            ["name" => "FROST", "county" => "NAVARRO"],
            ["name" => "KERENS", "county" => "NAVARRO"],
            ["name" => "POWELL", "county" => "NAVARRO"],
            ["name" => "PURDON", "county" => "NAVARRO"],
            ["name" => "RICE", "county" => "NAVARRO"],
            ["name" => "RICHLAND", "county" => "NAVARRO"],
            ["name" => "BON WIER", "county" => "NEWTON"],
            ["name" => "BURKEVILLE", "county" => "NEWTON"],
            ["name" => "CALL", "county" => "NEWTON"],
            ["name" => "DEWEYVILLE", "county" => "NEWTON"],
            ["name" => "NEWTON", "county" => "NEWTON"],
            ["name" => "WIERGATE", "county" => "NEWTON"],
            ["name" => "BLACKWELL", "county" => "NOLAN"],
            ["name" => "MARYNEAL", "county" => "NOLAN"],
            ["name" => "NOLAN", "county" => "NOLAN"],
            ["name" => "ROSCOE", "county" => "NOLAN"],
            ["name" => "SWEETWATER", "county" => "NOLAN"],
            ["name" => "AGUA DULCE", "county" => "NUECES"],
            ["name" => "BANQUETE", "county" => "NUECES"],
            ["name" => "BISHOP", "county" => "NUECES"],
            ["name" => "CHAPMAN RANCH", "county" => "NUECES"],
            ["name" => "CORPUS CHRISTI", "county" => "NUECES"],
            ["name" => "CRP CHRISTI", "county" => "NUECES"],
            ["name" => "DRISCOLL", "county" => "NUECES"],
            ["name" => "PORT", "county" => "NUECES"],
            ["name" => "ROBSTOWN", "county" => "NUECES"],
            ["name" => "FARNSWORTH", "county" => "OCHILTREE"],
            ["name" => "PERRYTON", "county" => "OCHILTREE"],
            ["name" => "WAKA", "county" => "OCHILTREE"],
            ["name" => "ADRIAN", "county" => "OLDHAM"],
            ["name" => "BOYS RANCH", "county" => "OLDHAM"],
            ["name" => "VEGA", "county" => "OLDHAM"],
            ["name" => "WILDORADO", "county" => "OLDHAM"],
            ["name" => "BRIDGE CITY", "county" => "ORANGE"],
            ["name" => "MAURICEVILLE", "county" => "ORANGE"],
            ["name" => "ORANGE", "county" => "ORANGE"],
            ["name" => "ORANGEFIELD", "county" => "ORANGE"],
            ["name" => "VIDOR", "county" => "ORANGE"],
            ["name" => "GORDON", "county" => "PALO PINTO"],
            ["name" => "GRAFORD", "county" => "PALO PINTO"],
            ["name" => "MINERAL WELLS", "county" => "PALO PINTO"],
            ["name" => "MINGUS", "county" => "PALO PINTO"],
            ["name" => "PALO PINTO", "county" => "PALO PINTO"],
            ["name" => "SANTO	PALO", "county" => "PALO PINTO"],
            ["name" => "STRAWN", "county" => "PALO PINTO"],
            ["name" => "BECKVILLE", "county" => "PANOLA"],
            ["name" => "CARTHAGE", "county" => "PANOLA"],
            ["name" => "CLAYTON", "county" => "PANOLA"],
            ["name" => "DE BERRY", "county" => "PANOLA"],
            ["name" => "GARY", "county" => "PANOLA"],
            ["name" => "LONG BRANCH", "county" => "PANOLA"],
            ["name" => "PANOLA", "county" => "PANOLA"],
            ["name" => "ALEDO", "county" => "PARKER"],
            ["name" => "AZLE", "county" => "PARKER"],
            ["name" => "DENNIS", "county" => "PARKER"],
            ["name" => "MILLSAP", "county" => "PARKER"],
            ["name" => "PEASTER", "county" => "PARKER"],
            ["name" => "POOLVILLE", "county" => "PARKER"],
            ["name" => "SPRINGTOWN", "county" => "PARKER"],
            ["name" => "WEATHERFORD", "county" => "PARKER"],
            ["name" => "WHITT", "county" => "PARKER"],
            ["name" => "BOVINA", "county" => "PARMER"],
            ["name" => "FARWELL", "county" => "PARMER"],
            ["name" => "FRIONA", "county" => "PARMER"],
            ["name" => "LAZBUDDIE", "county" => "PARMER"],
            ["name" => "COYANOSA", "county" => "PECOS"],
            ["name" => "FORT STOCKTON", "county" => "PECOS"],
            ["name" => "GIRVIN", "county" => "PECOS"],
            ["name" => "IMPERIAL", "county" => "PECOS"],
            ["name" => "IRAAN", "county" => "PECOS"],
            ["name" => "SHEFFIELD", "county" => "PECOS"],
            ["name" => "ACE", "county" => "POLK"],
            ["name" => "CAMDEN", "county" => "POLK"],
            ["name" => "CORRIGAN", "county" => "POLK"],
            ["name" => "DALLARDSVILLE", "county" => "POLK"],
            ["name" => "GOODRICH", "county" => "POLK"],
            ["name" => "LEGGETT", "county" => "POLK"],
            ["name" => "LIVINGSTON", "county" => "POLK"],
            ["name" => "MOSCOW", "county" => "POLK"],
            ["name" => "ONALASKA", "county" => "POTTER"],
            ["name" => "AMARILLO", "county" => "POTTER"],
            ["name" => "BUSHLAND", "county" => "POTTER"],
            ["name" => "MARFA", "county" => "PRESIDIO"],
            ["name" => "PRESIDIO", "county" => "PRESIDIO"],
            ["name" => "REDFORD", "county" => "PRESIDIO"],
            ["name" => "VALENTINE", "county" => "PRESIDIO"],
            ["name" => "EMORY", "county" => "RAINS"],
            ["name" => "POINT", "county" => "RAINS"],
            ["name" => "AMARILLO", "county" => "RANDALL"],
            ["name" => "CANYON", "county" => "RANDALL"],
            ["name" => "UMBARGER", "county" => "RANDALL"],
            ["name" => "BIG LAKE", "county" => "REAGAN"],
            ["name" => "CAMP WOOD", "county" => "REAL"],
            ["name" => "LEAKEY", "county" => "REAL"],
            ["name" => "RIO FRIO", "county" => "REAL"],
            ["name" => "ANNONA", "county" => "RED RIVER"],
            ["name" => "AVERY	RED", "county" => "RED RIVER"],
            ["name" => "BAGWELL", "county" => "RED RIVER"],
            ["name" => "BOGATA", "county" => "RED RIVER"],
            ["name" => "CLARKSVILLE", "county" => "RED RIVER"],
            ["name" => "DETROIT", "county" => "RED RIVER"],
            ["name" => "BALMORHEA", "county" => "REEVES"],
            ["name" => "ORLA", "county" => "REEVES"],
            ["name" => "PECOS", "county" => "REEVES"],
            ["name" => "SARAGOSA", "county" => "REEVES"],
            ["name" => "TOYAH", "county" => "REEVES"],
            ["name" => "TOYAHVALE", "county" => "REEVES"],
            ["name" => "AUSTWELL", "county" => "REFUGIO"],
            ["name" => "BAYSIDE", "county" => "REFUGIO"],
            ["name" => "REFUGIO", "county" => "REFUGIO"],
            ["name" => "TIVOLI", "county" => "REFUGIO"],
            ["name" => "WOODSBORO", "county" => "REFUGIO"],
            ["name" => "MIAMI", "county" => "ROBERTS"],
            ["name" => "BREMOND", "county" => "ROBERTSON"],
            ["name" => "CALVERT", "county" => "ROBERTSON"],
            ["name" => "FRANKLIN", "county" => "ROBERTSON"],
            ["name" => "HEARNE", "county" => "ROBERTSON"],
            ["name" => "MUMFORD", "county" => "ROBERTSON"],
            ["name" => "NEW BADEN", "county" => "ROBERTSON"],
            ["name" => "WHEELOCK", "county" => "ROBERTSON"],
            ["name" => "FATE", "county" => "ROCKWALL"],
            ["name" => "ROCKWALL", "county" => "ROCKWALL"],
            ["name" => "ROYSE CITY", "county" => "ROCKWALL"],
            ["name" => "BALLINGER", "county" => "RUNNELS"],
            ["name" => "MILES", "county" => "RUNNELS"],
            ["name" => "NORTON", "county" => "RUNNELS"],
            ["name" => "ROWENA", "county" => "RUNNELS"],
            ["name" => "WINGATE", "county" => "RUNNELS"],
            ["name" => "WINTERS", "county" => "RUNNELS"],
            ["name" => "HENDERSON", "county" => "RUSK"],
            ["name" => "JOINERVILLE", "county" => "RUSK"],
            ["name" => "LAIRD HILL", "county" => "RUSK"],
            ["name" => "LANEVILLE", "county" => "RUSK"],
            ["name" => "MINDEN", "county" => "RUSK"],
            ["name" => "MOUNT ENTERPRISE", "county" => "RUSK"],
            ["name" => "NEW LONDON", "county" => "RUSK"],
            ["name" => "OVERTON", "county" => "RUSK"],
            ["name" => "PRICE", "county" => "RUSK"],
            ["name" => "SELMAN CITY", "county" => "RUSK"],
            ["name" => "TATUM", "county" => "RUSK"],
            ["name" => "BRONSON", "county" => "SABINE"],
            ["name" => "HEMPHILL", "county" => "SABINE"],
            ["name" => "MILAM", "county" => "SABINE"],
            ["name" => "PINELAND", "county" => "SAN AUGUSTINE"],
            ["name" => "BROADDUS", "county" => "SAN AUGUSTINE"],
            ["name" => "SAN AUGUSTINE", "county" => "SAN AUGUSTINE"],
            ["name" => "COLDSPRING", "county" => "SAN JACINTO"],
            ["name" => "OAKHURST", "county" => "SAN JACINTO"],
            ["name" => "POINTBLANK", "county" => "SAN JACINTO"],
            ["name" => "SHEPHERD", "county" => "SAN JACINTO"],
            ["name" => "ARANSAS PASS", "county" => "SAN PATRICIO"],
            ["name" => "EDROY", "county" => "SAN PATRICIO"],
            ["name" => "GREGORY", "county" => "SAN PATRICIO"],
            ["name" => "INGLESIDE", "county" => "SAN PATRICIO"],
            ["name" => "MATHIS", "county" => "SAN PATRICIO"],
            ["name" => "ODEM", "county" => "SAN PATRICIO"],
            ["name" => "PORTLAND", "county" => "SAN PATRICIO"],
            ["name" => "SINTON", "county" => "SAN PATRICIO"],
            ["name" => "TAFT", "county" => "SAN PATRICIO"],
            ["name" => "BEND", "county" => "SAN SABA"],
            ["name" => "CHEROKEE", "county" => "SAN SABA"],
            ["name" => "RICHLAND SPRINGS", "county" => "SAN SABA"],
            ["name" => "SAN SABA", "county" => "SAN SABA"],
            ["name" => "ELDORADO", "county" => "SCHLEICHER"],
            ["name" => "DUNN", "county" => "SCURRY"],
            ["name" => "FLUVANNA", "county" => "SCURRY"],
            ["name" => "HERMLEIGH", "county" => "SCURRY"],
            ["name" => "IRA", "county" => "SCURRY"],
            ["name" => "SNYDER", "county" => "SCURRY"],
            ["name" => "ALBANY", "county" => "SHACKELFORD"],
            ["name" => "MORAN", "county" => "SHACKELFORD"],
            ["name" => "CENTER", "county" => "SHELBY"],
            ["name" => "JOAQUIN", "county" => "SHELBY"],
            ["name" => "SHELBYVILLE", "county" => "SHELBY"],
            ["name" => "TENAHA", "county" => "SHELBY"],
            ["name" => "TIMPSON", "county" => "SHELBY"],
            ["name" => "STRATFORD", "county" => "SHERMAN"],
            ["name" => "TEXHOMA", "county" => "SHERMAN"],
            ["name" => "ARP", "county" => "SMITH"],
            ["name" => "BULLARD", "county" => "SMITH"],
            ["name" => "FLINT", "county" => "SMITH"],
            ["name" => "LINDALE", "county" => "SMITH"],
            ["name" => "TROUP", "county" => "SMITH"],
            ["name" => "TYLER", "county" => "SMITH"],
            ["name" => "WHITEHOUSE", "county" => "SMITH"],
            ["name" => "WINONA", "county" => "SMITH"],
            ["name" => "GLEN ROSE", "county" => "SOMERVELL"],
            ["name" => "NEMO", "county" => "SOMERVELL"],
            ["name" => "RAINBOW", "county" => "SOMERVELL"],
            ["name" => "DELMITA", "county" => "STARR"],
            ["name" => "FALCON HEIGHTS", "county" => "STARR"],
            ["name" => "GARCIASVILLE", "county" => "STARR"],
            ["name" => "GRULLA", "county" => "STARR"],
            ["name" => "RIO GRANDE CITY", "county" => "STARR"],
            ["name" => "ROMA", "county" => "STARR"],
            ["name" => "SALINENO", "county" => "STARR"],
            ["name" => "SAN ISIDRO", "county" => "STARR"],
            ["name" => "SANTA ELENA", "county" => "STARR"],
            ["name" => "BRECKENRIDGE", "county" => "STEPHENS"],
            ["name" => "CADDO", "county" => "STEPHENS"],
            ["name" => "STERLING CITY", "county" => "STERLING"],
            ["name" => "ASPERMONT", "county" => "STONEWALL"],
            ["name" => "OLD GLORY", "county" => "STONEWALL"],
            ["name" => "SONORA", "county" => "SUTTON"],
            ["name" => "HAPPY", "county" => "SWISHER"],
            ["name" => "KRESS", "county" => "SWISHER"],
            ["name" => "TULIA", "county" => "SWISHER"],
            ["name" => "ARLINGTON", "county" => "TARRANT"],
            ["name" => "AZLE", "county" => "TARRANT"],
            ["name" => "BEDFORD", "county" => "TARRANT"],
            ["name" => "COLLEYVILLE", "county" => "TARRANT"],
            ["name" => "CROWLEY", "county" => "TARRANT"],
            ["name" => "EULESS", "county" => "TARRANT"],
            ["name" => "FORT WORTH", "county" => "TARRANT"],
            ["name" => "GRAPEVINE", "county" => "TARRANT"],
            ["name" => "HALTOM CITY", "county" => "TARRANT"],
            ["name" => "HASLET", "county" => "TARRANT"],
            ["name" => "HURST", "county" => "TARRANT"],
            ["name" => "KELLER", "county" => "TARRANT"],
            ["name" => "KENNEDALE", "county" => "TARRANT"],
            ["name" => "MANSFIELD", "county" => "TARRANT"],
            ["name" => "NAVAL AIR STATION/ JRB", "county" => "TARRANT"],
            ["name" => "NORTH RICHLAND HILLS", "county" => "TARRANT"],
            ["name" => "SOUTHLAKE", "county" => "TARRANT"],
            ["name" => "ABILENE", "county" => "TAYLOR"],
            ["name" => "BUFFALO GAP", "county" => "TAYLOR"],
            ["name" => "DYESS AFB", "county" => "TAYLOR"],
            ["name" => "LAWN", "county" => "TAYLOR"],
            ["name" => "MERKEL", "county" => "TAYLOR"],
            ["name" => "OVALO", "county" => "TAYLOR"],
            ["name" => "TRENT", "county" => "TAYLOR"],
            ["name" => "TUSCOLA", "county" => "TAYLOR"],
            ["name" => "TYE", "county" => "TAYLOR"],
            ["name" => "DRYDEN", "county" => "TERRELL"],
            ["name" => "SANDERSON", "county" => "TERRELL"],
            ["name" => "BROWNFIELD", "county" => "TERRY"],
            ["name" => "MEADOW", "county" => "TERRY"],
            ["name" => "WELLMAN", "county" => "TERRY"],
            ["name" => "THROCKMORTON", "county" => "THROCKMORTON"],
            ["name" => "WOODSON", "county" => "THROCKMORTON"],
            ["name" => "COOKVILLE", "county" => "TITUS"],
            ["name" => "MOUNT PLEASANT", "county" => "TITUS"],
            ["name" => "WINFIELD", "county" => "TITUS"],
            ["name" => "CARLSBAD", "county" => "TOM GREEN"],
            ["name" => "CHRISTOVAL", "county" => "TOM GREEN"],
            ["name" => "GOODFELLOW AFB", "county" => "TOM GREEN"],
            ["name" => "KNICKERBOCKER", "county" => "TOM GREEN"],
            ["name" => "MERETA", "county" => "TOM GREEN"],
            ["name" => "SAN ANGELO", "county" => "TOM GREEN"],
            ["name" => "VANCOURT", "county" => "TOM GREEN"],
            ["name" => "VERIBEST", "county" => "TOM GREEN"],
            ["name" => "WALL", "county" => "TOM GREEN"],
            ["name" => "WATER VALLEY", "county" => "TOM GREEN"],
            ["name" => "AUSTIN", "county" => "TRAVIS"],
            ["name" => "DEL VALLE	", "county" => "TRAVIS"],
            ["name" => "LEANDER", "county" => "TRAVIS"],
            ["name" => "MANCHACA", "county" => "TRAVIS"],
            ["name" => "MANOR", "county" => "TRAVIS"],
            ["name" => "MC NEIL", "county" => "TRAVIS"],
            ["name" => "PFLUGERVILLE", "county" => "TRAVIS"],
            ["name" => "SPICEWOOD", "county" => "TRAVIS"],
            ["name" => "APPLE SPRINGS", "county" => "TRINITY"],
            ["name" => "CENTRALIA", "county" => "TRINITY"],
            ["name" => "GROVETON", "county" => "TRINITY"],
            ["name" => "PENNINGTON", "county" => "TRINITY"],
            ["name" => "TRINITY", "county" => "TRINITY"],
            ["name" => "WOODLAKE", "county" => "TRINITY"],
            ["name" => "CHESTER", "county" => "TYLER"],
            ["name" => "COLMESNEIL", "county" => "TYLER"],
            ["name" => "DOUCETTE", "county" => "TYLER"],
            ["name" => "FRED", "county" => "TYLER"],
            ["name" => "HILLISTER", "county" => "TYLER"],
            ["name" => "SPURGER", "county" => "TYLER"],
            ["name" => "WARREN", "county" => "TYLER"],
            ["name" => "WOODVILLE", "county" => "TYLER"],
            ["name" => "BIG SANDY", "county" => "UPSHUR"],
            ["name" => "DIANA", "county" => "UPSHUR"],
            ["name" => "GILMER", "county" => "UPSHUR"],
            ["name" => "ORE CITY", "county" => "UPSHUR"],
            ["name" => "MC CAMEY", "county" => "UPTON"],
            ["name" => "MIDKIFF", "county" => "UPTON"],
            ["name" => "RANKIN", "county" => "UPTON"],
            ["name" => "CONCAN", "county" => "UVALDE"],
            ["name" => "KNIPPA", "county" => "UVALDE"],
            ["name" => "SABINAL", "county" => "UVALDE"],
            ["name" => "UTOPIA", "county" => "UVALDE"],
            ["name" => "UVALDE", "county" => "UVALDE"],
            ["name" => "COMSTOCK", "county" => "VAL VERDE"],
            ["name" => "DEL RIO", "county" => "VAL VERDE"],
            ["name" => "LANGTRY", "county" => "VAL VERDE"],
            ["name" => "LAUGHLIN AFB", "county" => "VAL VERDE"],
            ["name" => "BEN WHEELER", "county" => "VAN ZANDT"],
            ["name" => "CANTON", "county" => "VAN ZANDT"],
            ["name" => "EDGEWOOD", "county" => "VAN ZANDT"],
            ["name" => "FRUITVALE", "county" => "VAN ZANDT"],
            ["name" => "GRAND SALINE", "county" => "VAN ZANDT"],
            ["name" => "VAN", "county" => "VAN ZANDT"],
            ["name" => "WILLS POINT", "county" => "VAN ZANDT"],
            ["name" => "BLOOMINGTON", "county" => "VICTORIA"],
            ["name" => "INEZ", "county" => "VICTORIA"],
            ["name" => "MCFADDIN", "county" => "VICTORIA"],
            ["name" => "NURSERY", "county" => "VICTORIA"],
            ["name" => "PLACEDO", "county" => "VICTORIA"],
            ["name" => "TELFERNER", "county" => "VICTORIA"],
            ["name" => "VICTORIA", "county" => "VICTORIA"],
            ["name" => "DODGE", "county" => "WALKER"],
            ["name" => "HUNTSVILLE", "county" => "WALKER"],
            ["name" => "NEW WAVERLY", "county" => "WALKER"],
            ["name" => "RIVERSIDE", "county" => "WALKER"],
            ["name" => "BROOKSHIRE", "county" => "WALLER"],
            ["name" => "HEMPSTEAD", "county" => "WALLER"],
            ["name" => "PATTISON", "county" => "WALLER"],
            ["name" => "PRAIRIE VIEW", "county" => "WALLER"],
            ["name" => "BARSTOW", "county" => "WARD"],
            ["name" => "GRANDFALLS", "county" => "WARD"],
            ["name" => "MONAHANS", "county" => "WARD"],
            ["name" => "PYOTE", "county" => "WARD"],
            ["name" => "WICKETT", "county" => "WARD"],
            ["name" => "BRENHAM", "county" => "WASHINGTON"],
            ["name" => "BURTON", "county" => "WASHINGTON"],
            ["name" => "CHAPPELL HILL", "county" => "WASHINGTON"],
            ["name" => "WASHINGTON", "county" => "WASHINGTON"],
            ["name" => "BRUNI", "county" => "WEBB"],
            ["name" => "LAREDO", "county" => "WEBB"],
            ["name" => "MIRANDO CITY", "county" => "WEBB"],
            ["name" => "OILTON", "county" => "WEBB"],
            ["name" => "BOLING", "county" => "WHARTON"],
            ["name" => "DANEVANG", "county" => "WHARTON"],
            ["name" => "EAST BERNARD", "county" => "WHARTON"],
            ["name" => "EGYPT", "county" => "WHARTON"],
            ["name" => "EL CAMPO", "county" => "WHARTON"],
            ["name" => "GLEN FLORA", "county" => "county"],
            ["name" => "HUNGERFORD", "county" => "WHARTON"],
            ["name" => "LANE CITY", "county" => "WHARTON"],
            ["name" => "LISSIE", "county" => "WHARTON"],
            ["name" => "LOUISE", "county" => "WHARTON"],
            ["name" => "PIERCE", "county" => "WHARTON"],
            ["name" => "WHARTON", "county" => "WHARTON"],
            ["name" => "ALLISON", "county" => "WHEELER"],
            ["name" => "BRISCOE", "county" => "WHEELER"],
            ["name" => "MOBEETIE", "county" => "WHEELER"],
            ["name" => "SHAMROCK", "county" => "WHEELER"],
            ["name" => "WHEELER", "county" => "WHEELER"],
            ["name" => "BURKBURNETT", "county" => "WICHITA"],
            ["name" => "ELECTRA", "county" => "WICHITA"],
            ["name" => "IOWA PARK", "county" => "WICHITA"],
            ["name" => "KAMAY", "county" => "WICHITA"],
            ["name" => "SHEPPARD AFB", "county" => "WICHITA"],
            ["name" => "WICHITA FALLS", "county" => "WICHITA"],
            ["name" => "HARROLD", "county" => "WILBARGER"],
            ["name" => "ODELL", "county" => "WILBARGER"],
            ["name" => "OKLAUNION", "county" => "WILBARGER"],
            ["name" => "VERNON", "county" => "WILBARGER"],
            ["name" => "LASARA", "county" => "WILLACY"],
            ["name" => "LYFORD", "county" => "WILLACY"],
            ["name" => "PORT MANSFIELD", "county" => "WILLACY"],
            ["name" => "RAYMONDVILLE", "county" => "WILLACYWILLACY"],
            ["name" => "SAN PERLITA", "county" => "WILLACY"],
            ["name" => "SEBASTIAN", "county" => "WILLACY"],
            ["name" => "AUSTIN", "county" => "WILLIAMSON"],
            ["name" => "CEDAR PARK", "county" => "WILLIAMSON"],
            ["name" => "COUPLAND", "county" => "WILLIAMSON"],
            ["name" => "FLORENCE", "county" => "WILLIAMSON"],
            ["name" => "GEORGETOWN", "county" => "WILLIAMSON"],
            ["name" => "GRANGER", "county" => "WILLIAMSON"],
            ["name" => "HUTTO", "county" => "WILLIAMSON"],
            ["name" => "JARRELL", "county" => "WILLIAMSON"],
            ["name" => "LEANDER", "county" => "WILLIAMSON"],
            ["name" => "LIBERTY HILL", "county" => "WILLIAMSON"],
            ["name" => "ROUND ROCK", "county" => "WILLIAMSON"],
            ["name" => "SCHWERTNER", "county" => "WILLIAMSON"],
            ["name" => "TAYLOR", "county" => "WILLIAMSON"],
            ["name" => "THRALL", "county" => "WILLIAMSON"],
            ["name" => "WALBURG", "county" => "WILLIAMSON"],
            ["name" => "WEIR", "county" => "WILLIAMSON"],
            ["name" => "FLORESVILLE", "county" => "WILSON"],
            ["name" => "LA VERNIA", "county" => "WILSON"],
            ["name" => "PANDORA", "county" => "WILSON"],
            ["name" => "POTH", "county" => "WILSON"],
            ["name" => "STOCKDALE", "county" => "WILSON"],
            ["name" => "SUTHERLAND SPRINGS", "county" => "WILSON"],
            ["name" => "KERMIT", "county" => "WINKLER"],
            ["name" => "WINK", "county" => "WINKLER"],
            ["name" => "ALVORD", "county" => "WISE"],
            ["name" => "BOYD", "county" => "WISE"],
            ["name" => "BRIDGEPORT", "county" => "WISE"],
            ["name" => "CHICO", "county" => "WISE"],
            ["name" => "DECATUR", "county" => "WISE"],
            ["name" => "GREENWOOD", "county" => "WISE"],
            ["name" => "NEWARK", "county" => "WISE"],
            ["name" => "PARADISE", "county" => "WISE"],
            ["name" => "RHOME", "county" => "WISE"],
            ["name" => "SLIDELL", "county" => "WISE"],
            ["name" => "ALBA", "county" => "WOOD"],
            ["name" => "GOLDEN", "county" => "WOOD"],
            ["name" => "HAWKINS", "county" => "WOOD"],
            ["name" => "MINEOLA", "county" => "WOOD"],
            ["name" => "QUITMAN", "county" => "WOOD"],
            ["name" => "WINNSBORO", "county" => "WOOD"],
            ["name" => "YANTIS", "county" => "WOOD"],
            ["name" => "DENVER CITY", "county" => "YOAKUM"],
            ["name" => "PLAINS", "county" => "YOAKUM"],
            ["name" => "TOKIO", "county" => "YOAKUM"],
            ["name" => "GRAHAM", "county" => "YOUNG"],
            ["name" => "LOVING", "county" => "YOUNG"],
            ["name" => "NEWCASTLE", "county" => "YOUNG"],
            ["name" => "OLNEY", "county" => "YOUNG"],
            ["name" => "SOUTH BEND", "county" => "YOUNG"],
            ["name" => "LOPENO", "county" => "ZAPATA"],
            ["name" => "SAN YGNACIO", "county" => "ZAPATA"],
            ["name" => "ZAPATA", "county" => "ZAPATA"],
            ["name" => "BATESVILLE", "county" => "ZAVALA"],
            ["name" => "CRYSTAL CITY", "county" => "ZAVALA"],
            ["name" => "LA PRYOR", "county" => "ZAVALA"],
        ];
    }
}
