<?php

namespace Thirty98\Seeder\States\Texas;

use Thirty98\API\Stdlib\Seeders\AbstractDatabaseSeeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class CountySeeder extends AbstractDatabaseSeeder
{
    public $state_code = 'TX';
    protected $table_name = 'counties';
    
    protected function executeSeeder()
    {
        foreach ($this->getCounties() AS $county) {
            
            $slug = $this->slugit($county['name']);
            $county['name'] = ucwords(strtolower($county['name']));
            
            $exists = DB::table($this->table_name)->where('slug', $slug)
                ->where('state_code', $this->state_code)
                ->first();
            
            if (!$exists) {
                $county['state_code'] = $this->state_code;
                $county['slug'] = $slug;
                DB::table($this->table_name)->insert($county);
            }
            
            continue;
        }
    }
    
    private function getCounties()
    {
        return [
            ['code' => '0001', 'name' => 'Anderson'],
            ['code' => '0002', 'name' => 'Andrews'],
            ['code' => '0003', 'name' => 'Angelina'],
            ['code' => '0004', 'name' => 'Aransas'],
            ['code' => '0005', 'name' => 'Archer'],
            ['code' => '0006', 'name' => 'Armstrong'],
            ['code' => '0007', 'name' => 'Atascosa'],
            ['code' => '0008', 'name' => 'Austin'],
            ['code' => '0009', 'name' => 'Bailey'],
            ['code' => '0010', 'name' => 'Bandera'],
            ['code' => '0011', 'name' => 'Bastrop'],
            ['code' => '0012', 'name' => 'Baylor'],
            ['code' => '0013', 'name' => 'Bee'],
            ['code' => '0014', 'name' => 'Bell'],
            ['code' => '0015', 'name' => 'Bexar'],
            ['code' => '0016', 'name' => 'Blanco'],
            ['code' => '0017', 'name' => 'Borden'],
            ['code' => '0018', 'name' => 'Bosque'],
            ['code' => '0019', 'name' => 'Bowie'],
            ['code' => '0021', 'name' => 'Brazoria'],
            ['code' => '0022', 'name' => 'Brazos'],
            ['code' => '0023', 'name' => 'Brewster'],
            ['code' => '0024', 'name' => 'Briscoe'],
            ['code' => '0025', 'name' => 'Brooks'],
            ['code' => '0026', 'name' => 'Brown'],
            ['code' => '0027', 'name' => 'Burleson'],
            ['code' => '0028', 'name' => 'Burnet'],
            ['code' => '0029', 'name' => 'Caldwell'],
            ['code' => '0030', 'name' => 'Calhoun'],
            ['code' => '0031', 'name' => 'Callahan'],
            ['code' => '0032', 'name' => 'Cameron'],
            ['code' => '0033', 'name' => 'Camp'],
            ['code' => '0034', 'name' => 'Carson'],
            ['code' => '0035', 'name' => 'Cass'],
            ['code' => '0036', 'name' => 'Castro'],
            ['code' => '0037', 'name' => 'Chambers'],
            ['code' => '0038', 'name' => 'Cherokee'],
            ['code' => '0039', 'name' => 'Childress'],
            ['code' => '0040', 'name' => 'Clay'],
            ['code' => '0041', 'name' => 'Cochran'],
            ['code' => '0042', 'name' => 'Coke'],
            ['code' => '0043', 'name' => 'Coleman'],
            ['code' => '0044', 'name' => 'Collin'],
            ['code' => '0045', 'name' => 'COLLINGSWORTH'],
            ['code' => '0046', 'name' => 'COLORADO'],
            ['code' => '0047', 'name' => 'COMAL'],
            ['code' => '0048', 'name' => 'COMANCHE'],
            ['code' => '0049', 'name' => 'CONCHO'],
            ['code' => '0050', 'name' => 'COOKE'],
            ['code' => '0051', 'name' => 'CORYELL'],
            ['code' => '0052', 'name' => 'COTTLE'],
            ['code' => '0053', 'name' => 'CRANE'],
            ['code' => '0054', 'name' => 'CROCKETT'],
            ['code' => '0055', 'name' => 'CULBERSON'],
            ['code' => '0056', 'name' => 'DALLAM'],
            ['code' => '0057', 'name' => 'DALLAS'],
            ['code' => '0058', 'name' => 'DAWSON'],
            ['code' => '0059', 'name' => 'DE WITT'],
            ['code' => '0060', 'name' => 'DEAF SMITH'],
            ['code' => '0061', 'name' => 'DELTA'],
            ['code' => '0062', 'name' => 'DENTON'],
            ['code' => '0063', 'name' => 'DICKENS'],
            ['code' => '0064', 'name' => 'DIMMIT'],
            ['code' => '0065', 'name' => 'DONLEY'],
            ['code' => '0066', 'name' => 'DUVAL'],
            ['code' => '0067', 'name' => 'EASTLAND'],
            ['code' => '0068', 'name' => 'ECTOR'],
            ['code' => '0069', 'name' => 'EDWARDS'],
            ['code' => '0070', 'name' => 'EL PASO'],
            ['code' => '0071', 'name' => 'ELLIS'],
            ['code' => '0072', 'name' => 'ERATH'],
            ['code' => '0073', 'name' => 'FALLS'],
            ['code' => '0074', 'name' => 'FANNIN'],
            ['code' => '0075', 'name' => 'FAYETTE'],
            ['code' => '0076', 'name' => 'FISHER'],
            ['code' => '0077', 'name' => 'FOARD'],
            ['code' => '0078', 'name' => 'FORT BEND'],
            ['code' => '0079', 'name' => 'FRANKLIN'],
            ['code' => '0080', 'name' => 'FREESTONE'],
            ['code' => '0081', 'name' => 'FRIO'],
            ['code' => '0082', 'name' => 'GAINES'],
            ['code' => '0083', 'name' => 'GALVESTON'],
            ['code' => '0084', 'name' => 'GARZA'],
            ['code' => '0085', 'name' => 'GILLESPIE'],
            ['code' => '0086', 'name' => 'GLASSCOCK'],
            ['code' => '0087', 'name' => 'GOLIAD'],
            ['code' => '0088', 'name' => 'GONZALES'],
            ['code' => '0089', 'name' => 'GRAY'],
            ['code' => '0090', 'name' => 'GRAYSON'],
            ['code' => '0091', 'name' => 'GREGG'],
            ['code' => '0092', 'name' => 'GRIMES'],
            ['code' => '0093', 'name' => 'GUADALUPE'],
            ['code' => '0094', 'name' => 'HALE'],
            ['code' => '0095', 'name' => 'HALL'],
            ['code' => '0096', 'name' => 'HAMILTON'],
            ['code' => '0097', 'name' => 'HANSFORD'],
            ['code' => '0098', 'name' => 'HARDEMAN'],
            ['code' => '0099', 'name' => 'HARDIN'],
            ['code' => '0100', 'name' => 'HARRIS'],
            ['code' => '0101', 'name' => 'HARRISON'],
            ['code' => '0102', 'name' => 'HARTLEY'],
            ['code' => '0103', 'name' => 'HASKELL'],
            ['code' => '0104', 'name' => 'HEMPHILL'],
            ['code' => '0105', 'name' => 'HENDERSON'],
            ['code' => '0106', 'name' => 'HIDALGO'],
            ['code' => '0107', 'name' => 'HILL'],
            ['code' => '0108', 'name' => 'HOCKLEY'],
            ['code' => '0109', 'name' => 'HOOD'],
            ['code' => '0110', 'name' => 'HOPKINS'],
            ['code' => '0111', 'name' => 'HOUSTON'],
            ['code' => '0112', 'name' => 'HOWARD'],
            ['code' => '0113', 'name' => 'HUDSPETH'],
            ['code' => '0114', 'name' => 'HUNT'],
            ['code' => '0115', 'name' => 'HUTCHINSON'],
            ['code' => '0116', 'name' => 'IRION'],
            ['code' => '0117', 'name' => 'JACK'],
            ['code' => '0118', 'name' => 'JACKSON'],
            ['code' => '0119', 'name' => 'JASPER'],
            ['code' => '0120', 'name' => 'JEFF DAVIS'],
            ['code' => '0121', 'name' => 'JEFFERSON'],
            ['code' => '0122', 'name' => 'JIM HOGG'],
            ['code' => '0123', 'name' => 'JIM WELLS'],
            ['code' => '0124', 'name' => 'JOHNSON'],
            ['code' => '0125', 'name' => 'JONES'],
            ['code' => '0126', 'name' => 'KARNES'],
            ['code' => '0127', 'name' => 'KAUFMAN'],
            ['code' => '0128', 'name' => 'KENDALL'],
            ['code' => '0129', 'name' => 'KENEDY'],
            ['code' => '0130', 'name' => 'KENT'],
            ['code' => '0131', 'name' => 'KERR'],
            ['code' => '0132', 'name' => 'KIMBLE'],
            ['code' => '0133', 'name' => 'KING'],
            ['code' => '0134', 'name' => 'KINNEY'],
            ['code' => '0135', 'name' => 'KLEBERG'],
            ['code' => '0136', 'name' => 'KNOX'],
            ['code' => '0137', 'name' => 'LA SALLE'],
            ['code' => '0138', 'name' => 'LAMAR'],
            ['code' => '0139', 'name' => 'LAMB'],
            ['code' => '0140', 'name' => 'LAMPASAS'],
            ['code' => '0141', 'name' => 'LAVACA'],
            ['code' => '0142', 'name' => 'LEE'],
            ['code' => '0143', 'name' => 'LEON'],
            ['code' => '0144', 'name' => 'LIBERTY'],
            ['code' => '0145', 'name' => 'LIMESTONE'],
            ['code' => '0147', 'name' => 'LIPSCOMB'],
            ['code' => '0148', 'name' => 'LIVE OAK'],
            ['code' => '0149', 'name' => 'LLANO'],
            ['code' => '0150', 'name' => 'LOVING'],
            ['code' => '0151', 'name' => 'LUBBOCK'],
            ['code' => '0152', 'name' => 'LYNN'],
            ['code' => '0153', 'name' => 'MADISON'],
            ['code' => '0154', 'name' => 'MARION'],
            ['code' => '0155', 'name' => 'MARTIN'],
            ['code' => '0156', 'name' => 'MASON'],
            ['code' => '0157', 'name' => 'MATAGORDA'],
            ['code' => '0158', 'name' => 'MAVERICK'],
            ['code' => '0159', 'name' => 'MCCULLOCH'],
            ['code' => '0160', 'name' => 'MCLENNAN'],
            ['code' => '0161', 'name' => 'MCMULLEN'],
            ['code' => '0162', 'name' => 'MEDINA'],
            ['code' => '0163', 'name' => 'MENARD'],
            ['code' => '0164', 'name' => 'MIDLAND'],
            ['code' => '0165', 'name' => 'MILAM'],
            ['code' => '0166', 'name' => 'MILLS'],
            ['code' => '0167', 'name' => 'MITCHELL'],
            ['code' => '0168', 'name' => 'MONTAGUE'],
            ['code' => '0169', 'name' => 'MONTGOMERY'],
            ['code' => '0170', 'name' => 'MOORE'],
            ['code' => '0171', 'name' => 'MORRIS'],
            ['code' => '0172', 'name' => 'MOTLEY'],
            ['code' => '0173', 'name' => 'NACOGDOCHES'],
            ['code' => '0174', 'name' => 'NAVARRO'],
            ['code' => '0175', 'name' => 'NEWTON'],
            ['code' => '0176', 'name' => 'NOLAN'],
            ['code' => '0177', 'name' => 'NUECES'],
            ['code' => '0178', 'name' => 'OCHILTREE'],
            ['code' => '0179', 'name' => 'OLDHAM'],
            ['code' => '0180', 'name' => 'ORANGE'],
            ['code' => '0181', 'name' => 'PALO PINTO'],
            ['code' => '0182', 'name' => 'PANOLA'],
            ['code' => '0183', 'name' => 'PARKER'],
            ['code' => '0184', 'name' => 'PARMER'],
            ['code' => '0185', 'name' => 'PECOS'],
            ['code' => '0186', 'name' => 'POLK'],
            ['code' => '0187', 'name' => 'POTTER'],
            ['code' => '0188', 'name' => 'PRESIDIO'],
            ['code' => '0189', 'name' => 'RAINS'],
            ['code' => '0190', 'name' => 'RANDALL'],
            ['code' => '0191', 'name' => 'REAGAN'],
            ['code' => '0192', 'name' => 'REAL'],
            ['code' => '0193', 'name' => 'RED RIVER'],
            ['code' => '0194', 'name' => 'REEVES'],
            ['code' => '0195', 'name' => 'REFUGIO'],
            ['code' => '0196', 'name' => 'ROBERTS'],
            ['code' => '0197', 'name' => 'ROBERTSON'],
            ['code' => '0198', 'name' => 'ROCKWALL'],
            ['code' => '0199', 'name' => 'RUNNELS'],
            ['code' => '0200', 'name' => 'RUSK'],
            ['code' => '0201', 'name' => 'SABINE'],
            ['code' => '0202', 'name' => 'SAN AUGUSTINE'],
            ['code' => '0203', 'name' => 'SAN JACINTO'],
            ['code' => '0204', 'name' => 'SAN PATRICIO'],
            ['code' => '0205', 'name' => 'SAN SABA'],
            ['code' => '0206', 'name' => 'SCHLEICHER'],
            ['code' => '0207', 'name' => 'SCURRY'],
            ['code' => '0208', 'name' => 'SHACKELFORD'],
            ['code' => '0209', 'name' => 'SHELBY'],
            ['code' => '0210', 'name' => 'SHERMAN'],
            ['code' => '0211', 'name' => 'SMITH'],
            ['code' => '0212', 'name' => 'SOMERVELL'],
            ['code' => '0213', 'name' => 'STARR'],
            ['code' => '0214', 'name' => 'STEPHENS'],
            ['code' => '0215', 'name' => 'STERLING'],
            ['code' => '0216', 'name' => 'STONEWALL'],
            ['code' => '0217', 'name' => 'SUTTON'],
            ['code' => '0218', 'name' => 'SWISHER'],
            ['code' => '0219', 'name' => 'TARRANT'],
            ['code' => '0220', 'name' => 'TAYLOR'],
            ['code' => '0221', 'name' => 'TERRELL'],
            ['code' => '0222', 'name' => 'TERRY'],
            ['code' => '0223', 'name' => 'THROCKMORTON'],
            ['code' => '0224', 'name' => 'TITUS'],
            ['code' => '0225', 'name' => 'TOM GREEN'],
            ['code' => '0226', 'name' => 'TRAVIS'],
            ['code' => '0227', 'name' => 'TRINITY'],
            ['code' => '0228', 'name' => 'TYLER'],
            ['code' => '0229', 'name' => 'UPSHUR'],
            ['code' => '0230', 'name' => 'UPTON'],
            ['code' => '0231', 'name' => 'UVALDE'],
            ['code' => '0232', 'name' => 'VAL VERDE'],
            ['code' => '0233', 'name' => 'VAN ZANDT'],
            ['code' => '0234', 'name' => 'VICTORIA'],
            ['code' => '0235', 'name' => 'WALKER'],
            ['code' => '0236', 'name' => 'WALLER'],
            ['code' => '0237', 'name' => 'WARD'],
            ['code' => '0238', 'name' => 'WASHINGTON'],
            ['code' => '0239', 'name' => 'WEBB'],
            ['code' => '0240', 'name' => 'WHARTON'],
            ['code' => '0241', 'name' => 'WHEELER'],
            ['code' => '0242', 'name' => 'WICHITA'],
            ['code' => '0243', 'name' => 'WILBARGER'],
            ['code' => '0244', 'name' => 'WILLACY'],
            ['code' => '0245', 'name' => 'WILLIAMSON'],
            ['code' => '0246', 'name' => 'WILSON'],
            ['code' => '0247', 'name' => 'WINKLER'],
            ['code' => '0248', 'name' => 'WISE'],
            ['code' => '0249', 'name' => 'WOOD'],
            ['code' => '0250', 'name' => 'YOAKUM'],
            ['code' => '0251', 'name' => 'YOUNG'],
            ['code' => '0252', 'name' => 'ZAPATA'],
            ['code' => '0253', 'name' => 'ZAVALA']
        ];
    }
}
