<?php

namespace Thirty98\Seeder\States\Louisiana;

use Thirty98\API\Stdlib\AbstractDatabaseSeeder;
use Illuminate\Support\Facades\DB;
use Thirty98\Models\County;

class CitySeeder extends AbstractDatabaseSeeder
{
    public $state_code = 'LA';
    protected $table_name = 'cities';

    protected function executeSeeder()
    {
        // County index map.
        $counties = County::where('state_code', $this->state_code)->get();
        $countiesIndexes = [];

        foreach ($counties as $county) {
            $countiesIndexes[$county['slug']] = $county['id'];
        }

        foreach ($this->getCities() AS $city) {
            $countyID = $countiesIndexes[$this->slugit($city['county_name'])];

            $exists = DB::table($this->table_name)->where('slug', $city['slug'])
                ->where('county_id', $countyID)
                ->first();

            if (!$exists) {
                $insert_arr = [
                    'county_id' => $countyID,
                    'code' => $city['area_code'],
                    'name' => $city['name'],
                    'slug' => $city['slug']
                ];

                $result = DB::table($this->table_name)->insertGetId($insert_arr);

                if (!is_numeric($result)) {
                    die('City Inserted Failed for: ' . json_encode($insert_arr));
                }
            }

            continue;
        }
    }

    protected function getCities()
    {
        return [
            ['county_name' => 'Acadia', 'name' => 'Crowley', 'area_code' => '0101', 'slug' => $this->slugit('Crowley')],
            ['county_name' => 'Acadia', 'name' => 'Churchpoint', 'area_code' => '0102', 'slug' => $this->slugit('Churchpoint')],
            ['county_name' => 'Acadia', 'name' => 'Estherwood', 'area_code' => '0103', 'slug' => $this->slugit('Estherwood')],
            ['county_name' => 'Acadia', 'name' => 'Iota', 'area_code' => '0104', 'slug' => $this->slugit('Iota')],
            ['county_name' => 'Acadia', 'name' => 'Morse', 'area_code' => '0105', 'slug' => $this->slugit('Morse')],
            ['county_name' => 'Acadia', 'name' => 'Rayne', 'area_code' => '0106', 'slug' => $this->slugit('Rayne')],
            ['county_name' => 'Acadia', 'name' => 'Mermentau', 'area_code' => '0107', 'slug' => $this->slugit('Mermentau')],
            ['county_name' => 'Acadia', 'name' => 'Eunice', 'area_code' => '0108', 'slug' => $this->slugit('Eunice')],
            // ['county_name' => 'Acadia', 'name' => 'City Of Basile', 'area_code' => '0109', 'slug' => $this->slugit('City Of Basile')],
            ['county_name' => 'Acadia', 'name' => 'Basile', 'area_code' => '0109', 'slug' => $this->slugit('Basile')],
            ['county_name' => 'Acadia', 'name' => 'City Of Duson', 'area_code' => '0110', 'slug' => $this->slugit('City Of Duson')],
            ['county_name' => 'Allen', 'name' => 'Oakdale', 'area_code' => '0202', 'slug' => $this->slugit('Oakdale')],
            ['county_name' => 'Allen', 'name' => 'Oberlin', 'area_code' => '0203', 'slug' => $this->slugit('Oberlin')],
            ['county_name' => 'Allen', 'name' => 'Elizabeth', 'area_code' => '0204', 'slug' => $this->slugit('Elizabeth')],
            ['county_name' => 'Allen', 'name' => 'Kinder', 'area_code' => '0205', 'slug' => $this->slugit('Kinder')],
            ['county_name' => 'Allen', 'name' => 'Village Of Reeves', 'area_code' => '0206', 'slug' => $this->slugit('Village Of Reeves')],
            ['county_name' => 'Ascension East', 'name' => 'Gonzales', 'area_code' => '0302', 'slug' => $this->slugit('Gonzales')],
            ['county_name' => 'Ascension East', 'name' => 'East Ascension (East Bank)', 'area_code' => '0304', 'slug' => $this->slugit('East Ascension (East Bank)')],
            ['county_name' => 'Ascension East', 'name' => 'Sorrento', 'area_code' => '0305', 'slug' => $this->slugit('Sorrento')],
            ['county_name' => 'Ascension East', 'name' => 'Gonzales-Tanger Mall Dev Dist', 'area_code' => '0306', 'slug' => $this->slugit('Gonzales-Tanger Mall Dev Dist')],
            ['county_name' => 'Ascension West', 'name' => 'Donaldsonville', 'area_code' => '0301', 'slug' => $this->slugit('Donaldsonville')],
            ['county_name' => 'Ascension West', 'name' => 'West Ascension Hospital Service (West Bank)', 'area_code' => '0303', 'slug' => $this->slugit('West Ascension Hospital Service (West Bank)')],
            ['county_name' => 'Assumption', 'name' => 'Napoleonville', 'area_code' => '0401', 'slug' => $this->slugit('Napoleonville')],
            ['county_name' => 'Avoyelles', 'name' => 'Cottonport', 'area_code' => '0501', 'slug' => $this->slugit('Cottonport')],
            ['county_name' => 'Avoyelles', 'name' => 'Bunkie', 'area_code' => '0502', 'slug' => $this->slugit('Bunkie')],
            ['county_name' => 'Avoyelles', 'name' => 'Plaucheville', 'area_code' => '0503', 'slug' => $this->slugit('Plaucheville')],
            ['county_name' => 'Avoyelles', 'name' => 'Moreauville', 'area_code' => '0504', 'slug' => $this->slugit('Moreauville')],
            ['county_name' => 'Avoyelles', 'name' => 'Marksville', 'area_code' => '0505', 'slug' => $this->slugit('Marksville')],
            ['county_name' => 'Avoyelles', 'name' => 'Simmesport', 'area_code' => '0506', 'slug' => $this->slugit('Simmesport')],
            ['county_name' => 'Avoyelles', 'name' => 'Mansura', 'area_code' => '0507', 'slug' => $this->slugit('Mansura')],
            ['county_name' => 'Avoyelles', 'name' => 'Hessmer', 'area_code' => '0508', 'slug' => $this->slugit('Hessmer')],
            ['county_name' => 'Beauregard', 'name' => 'Deridder', 'area_code' => '0601', 'slug' => $this->slugit('Deridder')],
            ['county_name' => 'Beauregard', 'name' => 'Merryville', 'area_code' => '0602', 'slug' => $this->slugit('Merryville')],
            ['county_name' => 'Bienville', 'name' => 'Ringgold', 'area_code' => '0701', 'slug' => $this->slugit('Ringgold')],
            ['county_name' => 'Bienville', 'name' => 'Town Of Arcadia', 'area_code' => '0703', 'slug' => $this->slugit('Town Of Arcadia')],
            ['county_name' => 'Bienville', 'name' => 'Gibsland', 'area_code' => '0704', 'slug' => $this->slugit('Gibsland')],
            ['county_name' => 'Bienville', 'name' => 'Castor', 'area_code' => '0705', 'slug' => $this->slugit('Castor')],
            ['county_name' => 'Bienville', 'name' => 'Village Of Saline', 'area_code' => '0707', 'slug' => $this->slugit('Village Of Saline')],
            ['county_name' => 'Bossier', 'name' => 'Bossier City', 'area_code' => '0801', 'slug' => $this->slugit('Bossier City')],
            ['county_name' => 'Bossier', 'name' => 'Plain Dealing', 'area_code' => '0802', 'slug' => $this->slugit('Plain Dealing')],
            ['county_name' => 'Bossier', 'name' => 'Benton', 'area_code' => '0803', 'slug' => $this->slugit('Benton')],
            ['county_name' => 'Bossier', 'name' => 'Haughton', 'area_code' => '0804', 'slug' => $this->slugit('Haughton')],
            ['county_name' => 'Bossier', 'name' => 'Shreveport', 'area_code' => '0809', 'slug' => $this->slugit('Shreveport')],
            ['county_name' => 'Caddo', 'name' => 'Oil City', 'area_code' => '0902', 'slug' => $this->slugit('Oil City')],
            ['county_name' => 'Caddo', 'name' => 'Vivian', 'area_code' => '0903', 'slug' => $this->slugit('Vivian')],
            ['county_name' => 'Caddo', 'name' => 'Shreveport', 'area_code' => '0904', 'slug' => $this->slugit('Shreveport')],
            ['county_name' => 'Caddo', 'name' => 'Mooringsport', 'area_code' => '0905', 'slug' => $this->slugit('Mooringsport')],
            ['county_name' => 'Caddo', 'name' => 'Greenwood', 'area_code' => '0906', 'slug' => $this->slugit('Greenwood')],
            ['county_name' => 'Caddo', 'name' => 'Rodessa', 'area_code' => '0907', 'slug' => $this->slugit('Rodessa')],
            ['county_name' => 'Caddo', 'name' => 'Blanchard', 'area_code' => '0908', 'slug' => $this->slugit('Blanchard')],
            ['county_name' => 'Caddo', 'name' => 'Village Of Ida', 'area_code' => '0909', 'slug' => $this->slugit('Village Of Ida')],
            ['county_name' => 'Caddo', 'name' => 'N. Caddo Hospital Dist-Parish', 'area_code' => '0910', 'slug' => $this->slugit('N. Caddo Hospital Dist-Parish')],
            ['county_name' => 'Caddo', 'name' => 'Caddo Parish Fire District No.1', 'area_code' => '0912', 'slug' => $this->slugit('Caddo Parish Fire District No.1')],
            ['county_name' => 'Calcasieu', 'name' => 'Lake Charles', 'area_code' => '1001', 'slug' => $this->slugit('Lake Charles')],
            ['county_name' => 'Calcasieu', 'name' => 'Sulphur', 'area_code' => '1002', 'slug' => $this->slugit('Sulphur')],
            ['county_name' => 'Calcasieu', 'name' => 'Iowa', 'area_code' => '1003', 'slug' => $this->slugit('Iowa')],
            ['county_name' => 'Calcasieu', 'name' => 'Dequincy', 'area_code' => '1004', 'slug' => $this->slugit('Dequincy')],
            ['county_name' => 'Calcasieu', 'name' => 'Westlake', 'area_code' => '1005', 'slug' => $this->slugit('Westlake')],
            ['county_name' => 'Calcasieu', 'name' => 'Vinton', 'area_code' => '1006', 'slug' => $this->slugit('Vinton')],
            ['county_name' => 'Calcasieu', 'name' => 'Sales Tax Dist. 3 Unincorporated Ward #1 Only.', 'area_code' => '1007', 'slug' => $this->slugit('Sales Tax Dist. 3 Unincorporated Ward #1 Only.')],
            ['county_name' => 'Calcasieu', 'name' => 'Sales Tax District 4a', 'area_code' => '1008', 'slug' => $this->slugit('Sales Tax District 4a')],
            ['county_name' => 'Caldwell', 'name' => 'Columbia', 'area_code' => '1101', 'slug' => $this->slugit('Columbia')],
            ['county_name' => 'Claiborne', 'name' => 'Haynesville', 'area_code' => '1401', 'slug' => $this->slugit('Haynesville')],
            ['county_name' => 'Claiborne', 'name' => 'Homer', 'area_code' => '1402', 'slug' => $this->slugit('Homer')],
            ['county_name' => 'Claiborne', 'name' => 'Junction City', 'area_code' => '1403', 'slug' => $this->slugit('Junction City')],
            ['county_name' => 'Claiborne', 'name' => 'Village Of Athens', 'area_code' => '1404', 'slug' => $this->slugit('Village Of Athens')],
            ['county_name' => 'Concordia', 'name' => 'Vidalia', 'area_code' => '1501', 'slug' => $this->slugit('Vidalia')],
            ['county_name' => 'Concordia', 'name' => 'Ferriday', 'area_code' => '1502', 'slug' => $this->slugit('Ferriday')],
            ['county_name' => 'De Soto', 'name' => 'Logansport', 'area_code' => '1601', 'slug' => $this->slugit('Logansport')],
            ['county_name' => 'De Soto', 'name' => 'Mansfield', 'area_code' => '1602', 'slug' => $this->slugit('Mansfield')],
            ['county_name' => 'De Soto', 'name' => 'Stonewall', 'area_code' => '1603', 'slug' => $this->slugit('Stonewall')],
            ['county_name' => 'De Soto', 'name' => 'South Mansfield', 'area_code' => '1604', 'slug' => $this->slugit('South Mansfield')],
            ['county_name' => 'De Soto', 'name' => 'Grand Cane', 'area_code' => '1605', 'slug' => $this->slugit('Grand Cane')],
            ['county_name' => 'De Soto', 'name' => 'Keachi', 'area_code' => '1606', 'slug' => $this->slugit('Keachi')],
            ['county_name' => 'East Baton Rouge', 'name' => 'Baton Rouge/ Ebrp School District', 'area_code' => '1701', 'slug' => $this->slugit('Baton Rouge/ Ebrp School District')],
            ['county_name' => 'East Baton Rouge', 'name' => 'Baker/Baker School District', 'area_code' => '1702', 'slug' => $this->slugit('Baker/Baker School District')],
            ['county_name' => 'East Baton Rouge', 'name' => 'Central/Central School District', 'area_code' => '1703', 'slug' => $this->slugit('Central/Central School District')],
            ['county_name' => 'East Baton Rouge', 'name' => 'Zachary/Zachary School District', 'area_code' => '1705', 'slug' => $this->slugit('Zachary/Zachary School District')],
            ['county_name' => 'East Baton Rouge', 'name' => 'Zachary School Dist/Ebr Parish', 'area_code' => '1706', 'slug' => $this->slugit('Zachary School Dist/Ebr Parish')],
            ['county_name' => 'East Baton Rouge', 'name' => 'City Of Baker/Ebr Parish School Dist', 'area_code' => '1707', 'slug' => $this->slugit('City Of Baker/Ebr Parish School Dist')],
            ['county_name' => 'East Baton Rouge', 'name' => 'Ebr Parish/Central School Dist', 'area_code' => '1708', 'slug' => $this->slugit('Ebr Parish/Central School Dist')],
            ['county_name' => 'East Carroll', 'name' => 'Lake Providence', 'area_code' => '1801', 'slug' => $this->slugit('Lake Providence')],
            ['county_name' => 'Evangenline', 'name' => 'Ville Platte', 'area_code' => '2001', 'slug' => $this->slugit('Ville Platte')],
            ['county_name' => 'Evangenline', 'name' => 'Basile', 'area_code' => '2002', 'slug' => $this->slugit('Basile')],
            ['county_name' => 'Evangenline', 'name' => 'Mamou', 'area_code' => '2003', 'slug' => $this->slugit('Mamou')],
            ['county_name' => 'Evangenline', 'name' => 'Pine Prairie', 'area_code' => '2004', 'slug' => $this->slugit('Pine Prairie')],
            ['county_name' => 'Evangenline', 'name' => 'Chataignier', 'area_code' => '2005', 'slug' => $this->slugit('Chataignier')],
            ['county_name' => 'Evangenline', 'name' => 'Turkey Creek', 'area_code' => '2006', 'slug' => $this->slugit('Turkey Creek')],
            ['county_name' => 'Evangenline', 'name' => 'Rural Evangeline Except Ward 2', 'area_code' => '2007', 'slug' => $this->slugit('Rural Evangeline Except Ward 2')],
            ['county_name' => 'Evangenline', 'name' => 'Rural Evangeline Ward 2 Only', 'area_code' => '2008', 'slug' => $this->slugit('Rural Evangeline Ward 2 Only')],
            ['county_name' => 'Franklin', 'name' => 'Winnsboro', 'area_code' => '2101', 'slug' => $this->slugit('Winnsboro')],
            ['county_name' => 'Franklin', 'name' => 'Wisner', 'area_code' => '2102', 'slug' => $this->slugit('Wisner')],
            ['county_name' => 'Franklin', 'name' => 'Gilbert', 'area_code' => '2103', 'slug' => $this->slugit('Gilbert')],
            ['county_name' => 'Franklin', 'name' => 'Village Of Baskin', 'area_code' => '2104', 'slug' => $this->slugit('Village Of Baskin')],
            ['county_name' => 'Grant', 'name' => 'Colfax', 'area_code' => '2201', 'slug' => $this->slugit('Colfax')],
            ['county_name' => 'Grant', 'name' => 'Pollock', 'area_code' => '2202', 'slug' => $this->slugit('Pollock')],
            ['county_name' => 'Grant', 'name' => 'Georgetown', 'area_code' => '2203', 'slug' => $this->slugit('Georgetown')],
            ['county_name' => 'Grant', 'name' => 'Creola', 'area_code' => '2204', 'slug' => $this->slugit('Creola')],
            ['county_name' => 'Grant', 'name' => 'Montgomery', 'area_code' => '2205', 'slug' => $this->slugit('Montgomery')],
            ['county_name' => 'Grant', 'name' => 'Dry Prong', 'area_code' => '2206', 'slug' => $this->slugit('Dry Prong')],
            ['county_name' => 'Iberia', 'name' => 'Delcambre', 'area_code' => '2301', 'slug' => $this->slugit('Delcambre')],
            ['county_name' => 'Iberia', 'name' => 'New Iberia', 'area_code' => '2304', 'slug' => $this->slugit('New Iberia')],
            ['county_name' => 'Iberia', 'name' => 'Jeanerette', 'area_code' => '2305', 'slug' => $this->slugit('Jeanerette')],
            ['county_name' => 'Iberia', 'name' => 'Loreauville', 'area_code' => '2306', 'slug' => $this->slugit('Loreauville')],
            ['county_name' => 'Iberia', 'name' => 'Economic Development Dist. #1 (Tif Dist)', 'area_code' => '2307', 'slug' => $this->slugit('Economic Development Dist. #1 (Tif Dist)')],
            ['county_name' => 'Iberia', 'name' => 'City Of New Iberia Annexed Areas', 'area_code' => '2308', 'slug' => $this->slugit('City Of New Iberia Annexed Areas')],
            ['county_name' => 'Iberville', 'name' => 'St. Gabriel', 'area_code' => '2401', 'slug' => $this->slugit('St. Gabriel')],
            ['county_name' => 'Iberville', 'name' => 'University Club Center Edd', 'area_code' => '2401', 'slug' => $this->slugit('University Club Center Edd')],
            ['county_name' => 'Jackson', 'name' => 'Jonesboro', 'area_code' => '2501', 'slug' => $this->slugit('Jonesboro')],
            ['county_name' => 'Jackson', 'name' => 'Hodge', 'area_code' => '2502', 'slug' => $this->slugit('Hodge')],
            ['county_name' => 'Jackson', 'name' => 'East Hodge', 'area_code' => '2503', 'slug' => $this->slugit('East Hodge')],
            ['county_name' => 'Jackson', 'name' => 'North Hodge', 'area_code' => '2504', 'slug' => $this->slugit('North Hodge')],
            ['county_name' => 'Jackson', 'name' => 'Eros', 'area_code' => '2505', 'slug' => $this->slugit('Eros')],
            ['county_name' => 'Jackson', 'name' => 'Town Of Chatham', 'area_code' => '2506', 'slug' => $this->slugit('Town Of Chatham')],
            ['county_name' => 'Jefferson Davis', 'name' => 'Welsh', 'area_code' => '2701', 'slug' => $this->slugit('Welsh')],
            ['county_name' => 'Jefferson Davis', 'name' => 'Elton', 'area_code' => '2702', 'slug' => $this->slugit('Elton')],
            ['county_name' => 'Jefferson Davis', 'name' => 'Jennings', 'area_code' => '2703', 'slug' => $this->slugit('Jennings')],
            ['county_name' => 'Jefferson Davis', 'name' => 'Lake Arthur', 'area_code' => '2704', 'slug' => $this->slugit('Lake Arthur')],
            ['county_name' => 'Jefferson Davis', 'name' => 'Fenton', 'area_code' => '2705', 'slug' => $this->slugit('Fenton')],
            ['county_name' => 'Jefferson Davis', 'name' => 'Sales Tax District No. 1', 'area_code' => '2706', 'slug' => $this->slugit('Sales Tax District No. 1')],
            ['county_name' => 'Jefferson Davis', 'name' => 'Road Sales Tax District No 1', 'area_code' => '2707', 'slug' => $this->slugit('Road Sales Tax District No 1')],
            ['county_name' => 'Lafayette', 'name' => 'Lafayette City', 'area_code' => '2801', 'slug' => $this->slugit('Lafayette City')],
            ['county_name' => 'Lafayette', 'name' => 'Duson', 'area_code' => '2802', 'slug' => $this->slugit('Duson')],
            ['county_name' => 'Lafayette', 'name' => 'Carencro', 'area_code' => '2803', 'slug' => $this->slugit('Carencro')],
            ['county_name' => 'Lafayette', 'name' => 'Youngsville', 'area_code' => '2804', 'slug' => $this->slugit('Youngsville')],
            ['county_name' => 'Lafayette', 'name' => 'Scott', 'area_code' => '2805', 'slug' => $this->slugit('Scott')],
            ['county_name' => 'Lafayette', 'name' => 'Law Enforcement Sub-District #1 & Police Jury', 'area_code' => '2806', 'slug' => $this->slugit('Law Enforcement Sub-District #1 & Police Jury')],
            ['county_name' => 'Lafayette', 'name' => 'Broussard', 'area_code' => '2807', 'slug' => $this->slugit('Broussard')],
            ['county_name' => 'Lafayette', 'name' => 'Scott Apollo Dev Dist', 'area_code' => '2809', 'slug' => $this->slugit('Scott Apollo Dev Dist')],
            ['county_name' => 'Lafayette', 'name' => 'Scott Dest Pt Dev Dist', 'area_code' => '2810', 'slug' => $this->slugit('Scott Dest Pt Dev Dist')],
            ['county_name' => 'Lafayette', 'name' => 'Lafayette I-10 Corridor Dist @ Mile Marker 103', 'area_code' => '2812', 'slug' => $this->slugit('Lafayette I-10 Corridor Dist @ Mile Marker 103')],
            ['county_name' => 'Lafayette', 'name' => 'I-49 Economic Development District (Carencro Tif District)', 'area_code' => '2813', 'slug' => $this->slugit('I-49 Economic Development District (Carencro Tif District)')],
            ['county_name' => 'Lafourche', 'name' => 'Thibodaux', 'area_code' => '2901', 'slug' => $this->slugit('Thibodaux')],
            ['county_name' => 'Lafourche', 'name' => 'Lockport', 'area_code' => '2902', 'slug' => $this->slugit('Lockport')],
            ['county_name' => 'Lafourche', 'name' => 'Golden Meadow', 'area_code' => '2903', 'slug' => $this->slugit('Golden Meadow')],
            ['county_name' => 'Lafourche', 'name' => 'Road Tax Dist. 2', 'area_code' => '2904', 'slug' => $this->slugit('Road Tax Dist. 2')],
            ['county_name' => 'Lafourche', 'name' => 'South Lafourche Levee District', 'area_code' => '2908', 'slug' => $this->slugit('South Lafourche Levee District')],
            ['county_name' => 'Lafourche', 'name' => 'Road Sales Tax Dist 2 North', 'area_code' => '2902', 'slug' => $this->slugit('Road Sales Tax Dist 2 North')],
            ['county_name' => 'Lafourche', 'name' => 'Consolidated Dist A-Rd Dists 3, 5 & 6', 'area_code' => '2910', 'slug' => $this->slugit('Consolidated Dist A-Rd Dists 3, 5 & 6')],
            ['county_name' => 'Lasalle', 'name' => 'Jena', 'area_code' => '3001', 'slug' => $this->slugit('Jena')],
            ['county_name' => 'Lasalle', 'name' => 'Olla', 'area_code' => '3002', 'slug' => $this->slugit('Olla')],
            ['county_name' => 'Lincoln', 'name' => 'Ruston', 'area_code' => '3101', 'slug' => $this->slugit('Ruston')],
            ['county_name' => 'Lincoln', 'name' => 'Dubach', 'area_code' => '3102', 'slug' => $this->slugit('Dubach')],
            ['county_name' => 'Lincoln', 'name' => 'Grambling', 'area_code' => '3103', 'slug' => $this->slugit('Grambling')],
            ['county_name' => 'Lincoln', 'name' => 'Choudrant', 'area_code' => '3104', 'slug' => $this->slugit('Choudrant')],
            ['county_name' => 'Livingston', 'name' => 'Denham Springs', 'area_code' => '3201', 'slug' => $this->slugit('Denham Springs')],
            ['county_name' => 'Livingston', 'name' => 'Livingston', 'area_code' => '3202', 'slug' => $this->slugit('Livingston')],
            ['county_name' => 'Livingston', 'name' => 'Walker', 'area_code' => '3203', 'slug' => $this->slugit('Walker')],
            ['county_name' => 'Livingston', 'name' => 'Albany', 'area_code' => '3204', 'slug' => $this->slugit('Albany')],
            ['county_name' => 'Livingston', 'name' => 'Springfield', 'area_code' => '3205', 'slug' => $this->slugit('Springfield')],
            ['county_name' => 'Livingston', 'name' => 'Gravity Dr (Dist 1 Ward 2: Precincts 2-2-3, 2-2-3a, 2-2-6, 2-2-6a, & Dist 5 Portion 2-7-1)', 'area_code' => '3206', 'slug' => $this->slugit('Gravity Dr (Dist 1 Ward 2: Precincts 2-2-3, 2-2-3a, 2-2-6, 2-2-6a, & Dist 5 Portion 2-7-1)')],
            ['county_name' => 'Livingston', 'name' => 'Gravity Dr ( Dist 5 Precincts 1-11-1, 1-11-3, Portion Of 1-11-2)', 'area_code' => '3207', 'slug' => $this->slugit('Gravity Dr ( Dist 5 Precincts 1-11-1, 1-11-3, Portion Of 1-11-2)')],
            ['county_name' => 'Livingston', 'name' => 'Gravity Drainage Sales Tax District #6', 'area_code' => '3208', 'slug' => $this->slugit('Gravity Drainage Sales Tax District #6')],
            ['county_name' => 'Livingston', 'name' => 'School Tax District #22', 'area_code' => '3209', 'slug' => $this->slugit('School Tax District #22')],
            ['county_name' => 'Livingston', 'name' => 'Denham Springs Annexed Area', 'area_code' => '3210', 'slug' => $this->slugit('Denham Springs Annexed Area')],
            ['county_name' => 'Livingston', 'name' => 'Sales Tax District #33 (Maurapas)', 'area_code' => '3211', 'slug' => $this->slugit('Sales Tax District #33 (Maurapas)')],
            ['county_name' => 'Madison', 'name' => 'Tallulah', 'area_code' => '3301', 'slug' => $this->slugit('Tallulah')],
            ['county_name' => 'Madison', 'name' => 'Richmond', 'area_code' => '3302', 'slug' => $this->slugit('Richmond')],
            ['county_name' => 'Madison', 'name' => 'Delta', 'area_code' => '3303', 'slug' => $this->slugit('Delta')],
            ['county_name' => 'Morehouse', 'name' => 'Bastrop-(International Paper La. Mill)', 'area_code' => '3401', 'slug' => $this->slugit('Bastrop-(International Paper La. Mill)')],
            ['county_name' => 'Morehouse', 'name' => 'Mer Rouge', 'area_code' => '3402', 'slug' => $this->slugit('Mer Rouge')],
            ['county_name' => 'Morehouse', 'name' => 'Bonita', 'area_code' => '3403', 'slug' => $this->slugit('Bonita')],
            ['county_name' => 'Morehouse', 'name' => 'Collinston', 'area_code' => '3404', 'slug' => $this->slugit('Collinston')],
            ['county_name' => 'Morehouse', 'name' => 'East Morehouse Parish School District', 'area_code' => '3405', 'slug' => $this->slugit('East Morehouse Parish School District')],
            ['county_name' => 'Morehouse', 'name' => 'Sales Tax District #1-City Of Bastrop (Excluding International Paper Mill', 'area_code' => '3406', 'slug' => $this->slugit('Sales Tax District #1-City Of Bastrop (Excluding International Paper Mill')],
            ['county_name' => 'Morehouse', 'name' => 'Oak Ridge', 'area_code' => '3407', 'slug' => $this->slugit('Oak Ridge')],
            ['county_name' => 'Natchitoches', 'name' => 'Natchitoches', 'area_code' => '3503', 'slug' => $this->slugit('Natchitoches')],
            ['county_name' => 'Natchitoches', 'name' => 'Campti', 'area_code' => '3504', 'slug' => $this->slugit('Campti')],
            ['county_name' => 'Natchitoches', 'name' => 'Robeline', 'area_code' => '3505', 'slug' => $this->slugit('Robeline')],
            ['county_name' => 'Natchitoches', 'name' => 'Clarence', 'area_code' => '3506', 'slug' => $this->slugit('Clarence')],
            ['county_name' => 'Natchitoches', 'name' => 'Natchez', 'area_code' => '3507', 'slug' => $this->slugit('Natchez')],
            ['county_name' => 'Ouachita', 'name' => 'Monroe', 'area_code' => '3701', 'slug' => $this->slugit('Monroe')],
            ['county_name' => 'Ouachita', 'name' => 'West Monroe', 'area_code' => '3702', 'slug' => $this->slugit('West Monroe')],
            ['county_name' => 'Ouachita', 'name' => 'Sterlington', 'area_code' => '3703', 'slug' => $this->slugit('Sterlington')],
            ['county_name' => 'Ouachita', 'name' => 'Richwood', 'area_code' => '3704', 'slug' => $this->slugit('Richwood')],
            ['county_name' => 'Ouachita', 'name' => 'West Ouachita School District', 'area_code' => '3705', 'slug' => $this->slugit('West Ouachita School District')],
            ['county_name' => 'Pointe Coupee', 'name' => 'New Roads', 'area_code' => '3902', 'slug' => $this->slugit('New Roads')],
            ['county_name' => 'Pointe Coupee', 'name' => 'Morganza', 'area_code' => '3903', 'slug' => $this->slugit('Morganza')],
            ['county_name' => 'Pointe Coupee', 'name' => 'Livonia', 'area_code' => '3904', 'slug' => $this->slugit('Livonia')],
            ['county_name' => 'Pointe Coupee', 'name' => 'Fordoche', 'area_code' => '3905', 'slug' => $this->slugit('Fordoche')],
            ['county_name' => 'Rapides', 'name' => 'Alexandria', 'area_code' => '4001', 'slug' => $this->slugit('Alexandria')],
            ['county_name' => 'Rapides', 'name' => 'Pineville', 'area_code' => '4002', 'slug' => $this->slugit('Pineville')],
            ['county_name' => 'Rapides', 'name' => 'Glenmora', 'area_code' => '4003', 'slug' => $this->slugit('Glenmora')],
            ['county_name' => 'Rapides', 'name' => 'Lecompte', 'area_code' => '4004', 'slug' => $this->slugit('Lecompte')],
            ['county_name' => 'Rapides', 'name' => 'Ball', 'area_code' => '4005', 'slug' => $this->slugit('Ball')],
            ['county_name' => 'Rapides', 'name' => 'Boyce', 'area_code' => '4006', 'slug' => $this->slugit('Boyce')],
            ['county_name' => 'Rapides', 'name' => 'Woodworth', 'area_code' => '4007', 'slug' => $this->slugit('Woodworth')],
            ['county_name' => 'Rapides', 'name' => 'Village Of Forest Hill', 'area_code' => '4008', 'slug' => $this->slugit('Village Of Forest Hill')],
            ['county_name' => 'Rapides', 'name' => 'Town Of Cheneyville', 'area_code' => '4009', 'slug' => $this->slugit('Town Of Cheneyville')],
            ['county_name' => 'Rapides', 'name' => 'Fire District 17', 'area_code' => '4010', 'slug' => $this->slugit('Fire District 17')],
            ['county_name' => 'Red River', 'name' => 'Coushatta', 'area_code' => '4101', 'slug' => $this->slugit('Coushatta')],
            ['county_name' => 'Red River', 'name' => 'Hall Summit', 'area_code' => '4102', 'slug' => $this->slugit('Hall Summit')],
            ['county_name' => 'Richland', 'name' => 'Rayville', 'area_code' => '4201', 'slug' => $this->slugit('Rayville')],
            ['county_name' => 'Richland', 'name' => 'Mangham', 'area_code' => '4202', 'slug' => $this->slugit('Mangham')],
            ['county_name' => 'Richland', 'name' => 'Delhi', 'area_code' => '4203', 'slug' => $this->slugit('Delhi')],
            ['county_name' => 'Sabine', 'name' => 'Many', 'area_code' => '4301', 'slug' => $this->slugit('Many')],
            ['county_name' => 'Sabine', 'name' => 'Pleasant Hill', 'area_code' => '4302', 'slug' => $this->slugit('Pleasant Hill')],
            ['county_name' => 'Sabine', 'name' => 'Florien', 'area_code' => '4303', 'slug' => $this->slugit('Florien')],
            ['county_name' => 'Sabine', 'name' => 'Zwolle', 'area_code' => '4304', 'slug' => $this->slugit('Zwolle')],
            ['county_name' => 'Sabine', 'name' => 'Converse', 'area_code' => '4305', 'slug' => $this->slugit('Converse')],
            ['county_name' => 'Sabine', 'name' => 'Sales Tax District #1', 'area_code' => '4306', 'slug' => $this->slugit('Sales Tax District #1')],
            ['county_name' => 'St Helena', 'name' => 'Greensburg', 'area_code' => '4601', 'slug' => $this->slugit('Greensburg')],
            ['county_name' => 'St James', 'name' => 'Gramercy', 'area_code' => '4701', 'slug' => $this->slugit('Gramercy')],
            ['county_name' => 'St James', 'name' => 'Lutcher', 'area_code' => '4701', 'slug' => $this->slugit('Lutcher')],
            ['county_name' => 'St. Landry', 'name' => 'Opelousas', 'area_code' => '4901', 'slug' => $this->slugit('Opelousas')],
            ['county_name' => 'St. Landry', 'name' => 'Arnaudville', 'area_code' => '4902', 'slug' => $this->slugit('Arnaudville')],
            ['county_name' => 'St. Landry', 'name' => 'Eunice', 'area_code' => '4903', 'slug' => $this->slugit('Eunice')],
            ['county_name' => 'St. Landry', 'name' => 'Sunset', 'area_code' => '4904', 'slug' => $this->slugit('Sunset')],
            ['county_name' => 'St. Landry', 'name' => 'Port Barre', 'area_code' => '4905', 'slug' => $this->slugit('Port Barre')],
            ['county_name' => 'St. Landry', 'name' => 'Cankton', 'area_code' => '4906', 'slug' => $this->slugit('Cankton')],
            ['county_name' => 'St. Landry', 'name' => 'Grand Coteau', 'area_code' => '4907', 'slug' => $this->slugit('Grand Coteau')],
            ['county_name' => 'St. Landry', 'name' => 'Krotz Springs', 'area_code' => '4908', 'slug' => $this->slugit('Krotz Springs')],
            ['county_name' => 'St. Landry', 'name' => 'Washington', 'area_code' => '4909', 'slug' => $this->slugit('Washington')],
            ['county_name' => 'St. Landry', 'name' => 'Melville', 'area_code' => '4910', 'slug' => $this->slugit('Melville')],
            ['county_name' => 'St. Landry', 'name' => 'Town Of Leonville', 'area_code' => '4911', 'slug' => $this->slugit('Town Of Leonville')],
            ['county_name' => 'St. Landry', 'name' => 'Town Of Palmetto', 'area_code' => '4912', 'slug' => $this->slugit('Town Of Palmetto')],
            ['county_name' => 'St. Landry', 'name' => 'Harry Guilbeau Area Eco Dev', 'area_code' => '4913', 'slug' => $this->slugit('Harry Guilbeau Area Eco Dev')],
            ['county_name' => 'St Martin', 'name' => 'Arnaudville', 'area_code' => '5001', 'slug' => $this->slugit('Arnaudville')],
            ['county_name' => 'St Martin', 'name' => 'Breaux Bridge', 'area_code' => '5002', 'slug' => $this->slugit('Breaux Bridge')],
            ['county_name' => 'St Martin', 'name' => 'Henderson', 'area_code' => '5003', 'slug' => $this->slugit('Henderson')],
            ['county_name' => 'St Martin', 'name' => 'St. Martinville', 'area_code' => '5004', 'slug' => $this->slugit('St. Martinville')],
            ['county_name' => 'St Martin', 'name' => 'Parks', 'area_code' => '5005', 'slug' => $this->slugit('Parks')],
            ['county_name' => 'St Martin', 'name' => 'Sales Tax Dist #2', 'area_code' => '5006', 'slug' => $this->slugit('Sales Tax Dist #2')],
            ['county_name' => 'St Martin', 'name' => 'Sales Tax District #1', 'area_code' => '5007', 'slug' => $this->slugit('Sales Tax District #1')],
            ['county_name' => 'St Martin', 'name' => 'Broussard', 'area_code' => '5008', 'slug' => $this->slugit('Broussard')],
            ['county_name' => 'St Martin', 'name' => 'Breaux Bridge Annexed Area', 'area_code' => '5009', 'slug' => $this->slugit('Breaux Bridge Annexed Area')],
            ['county_name' => 'St Martin', 'name' => 'Breaux Bridge Economic Development Dist #1', 'area_code' => '5010', 'slug' => $this->slugit('Breaux Bridge Economic Development Dist #1')],
            ['county_name' => 'St Martin', 'name' => 'St Martinville Annex', 'area_code' => '5011', 'slug' => $this->slugit('St Martinville Annex')],
            ['county_name' => 'St Martin', 'name' => 'Henderson N I-10 Annex', 'area_code' => '5012', 'slug' => $this->slugit('Henderson N I-10 Annex')],
            ['county_name' => 'St Mary', 'name' => 'Do Not Use 5100 Should Use 5102, 5103, Or 5104', 'area_code' => '', 'slug' => $this->slugit('Do Not Use 5100 Should Use 5102, 5103, Or 5104')],
            ['county_name' => 'St Mary', 'name' => 'Morgan City', 'area_code' => '5101', 'slug' => $this->slugit('Morgan City')],
            ['county_name' => 'St Mary', 'name' => 'Wards 5 & 8 (Berwick, Patterson, Bayou Vista With A Morgan City Address)', 'area_code' => '5102', 'slug' => $this->slugit('Wards 5 & 8 (Berwick, Patterson, Bayou Vista With A Morgan City Address)')],
            ['county_name' => 'St Mary', 'name' => 'Wards 1,2,3,4,7 & 10 (Centerville, Franklin, Charenton, Garden City, Some Parts Of Jeanerette)', 'area_code' => '5103', 'slug' => $this->slugit('Wards 1,2,3,4,7 & 10 (Centerville, Franklin, Charenton, Garden City, Some Parts Of Jeanerette)')],
            ['county_name' => 'St Mary', 'name' => 'Wards 6 & 9 (Amelia & Siracusaville Which Use Morgan City Addresses With 70380 Zip Codes)', 'area_code' => '5104', 'slug' => $this->slugit('Wards 6 & 9 (Amelia & Siracusaville Which Use Morgan City Addresses With 70380 Zip Codes)')],
            ['county_name' => 'St Tammany', 'name' => 'Covington', 'area_code' => '5201', 'slug' => $this->slugit('Covington')],
            ['county_name' => 'St Tammany', 'name' => 'Abita Springs', 'area_code' => '5202', 'slug' => $this->slugit('Abita Springs')],
            ['county_name' => 'St Tammany', 'name' => 'Folsom', 'area_code' => '5203', 'slug' => $this->slugit('Folsom')],
            ['county_name' => 'St Tammany', 'name' => 'Madisonville', 'area_code' => '5204', 'slug' => $this->slugit('Madisonville')],
            ['county_name' => 'St Tammany', 'name' => 'Mandeville', 'area_code' => '5205', 'slug' => $this->slugit('Mandeville')],
            ['county_name' => 'St Tammany', 'name' => 'Pearl River', 'area_code' => '5206', 'slug' => $this->slugit('Pearl River')],
            ['county_name' => 'St Tammany', 'name' => 'Slidell', 'area_code' => '5207', 'slug' => $this->slugit('Slidell')],
            ['county_name' => 'St Tammany', 'name' => 'Sun', 'area_code' => '5208', 'slug' => $this->slugit('Sun')],
            ['county_name' => 'St Tammany', 'name' => 'Fremaux Economic Dev District', 'area_code' => '5209', 'slug' => $this->slugit('Fremaux Economic Dev District')],
            ['county_name' => 'St Tammany', 'name' => 'Nord Du Lac Economic Develop', 'area_code' => '5210', 'slug' => $this->slugit('Nord Du Lac Economic Develop')],
            ['county_name' => 'St Tammany', 'name' => 'Rooms To Go Econ Develop', 'area_code' => '5211', 'slug' => $this->slugit('Rooms To Go Econ Develop')],
            ['county_name' => 'St Tammany', 'name' => 'Northshore Square Economic Development Dist', 'area_code' => '5213', 'slug' => $this->slugit('Northshore Square Economic Development Dist')],
            ['county_name' => 'Tangipahoa', 'name' => 'Amite', 'area_code' => '5301', 'slug' => $this->slugit('Amite')],
            ['county_name' => 'Tangipahoa', 'name' => 'Hammond', 'area_code' => '5302', 'slug' => $this->slugit('Hammond')],
            ['county_name' => 'Tangipahoa', 'name' => 'Independence', 'area_code' => '5303', 'slug' => $this->slugit('Independence')],
            ['county_name' => 'Tangipahoa', 'name' => 'Ponchatoula', 'area_code' => '5304', 'slug' => $this->slugit('Ponchatoula')],
            ['county_name' => 'Tangipahoa', 'name' => 'Roseland', 'area_code' => '5305', 'slug' => $this->slugit('Roseland')],
            ['county_name' => 'Tangipahoa', 'name' => 'Kentwood', 'area_code' => '5306', 'slug' => $this->slugit('Kentwood')],
            ['county_name' => 'Tangipahoa', 'name' => 'Tangipahoa', 'area_code' => '5307', 'slug' => $this->slugit('Tangipahoa')],
            ['county_name' => 'Tangipahoa', 'name' => 'Tickfaw', 'area_code' => '5308', 'slug' => $this->slugit('Tickfaw')],
            ['county_name' => 'Tangipahoa', 'name' => 'Fire Protection District #1', 'area_code' => '5309', 'slug' => $this->slugit('Fire Protection District #1')],
            ['county_name' => 'Tensas', 'name' => 'Newellton', 'area_code' => '5401', 'slug' => $this->slugit('Newellton')],
            ['county_name' => 'Tensas', 'name' => 'St. Joseph', 'area_code' => '5402', 'slug' => $this->slugit('St. Joseph')],
            ['county_name' => 'Tensas', 'name' => 'Town Of Waterproof', 'area_code' => '5403', 'slug' => $this->slugit('Town Of Waterproof')],
            ['county_name' => 'Union', 'name' => 'Farmerville', 'area_code' => '5601', 'slug' => $this->slugit('Farmerville')],
            ['county_name' => 'Union', 'name' => 'Bernice', 'area_code' => '5602', 'slug' => $this->slugit('Bernice')],
            ['county_name' => 'Union', 'name' => 'Marion', 'area_code' => '5603', 'slug' => $this->slugit('Marion')],
            ['county_name' => 'Union', 'name' => 'Junction City', 'area_code' => '5604', 'slug' => $this->slugit('Junction City')],
            ['county_name' => 'Vermilion', 'name' => 'Abbeville', 'area_code' => '5701', 'slug' => $this->slugit('Abbeville')],
            ['county_name' => 'Vermilion', 'name' => 'Delcambre', 'area_code' => '5702', 'slug' => $this->slugit('Delcambre')],
            ['county_name' => 'Vermilion', 'name' => 'Erath', 'area_code' => '5703', 'slug' => $this->slugit('Erath')],
            ['county_name' => 'Vermilion', 'name' => 'Kaplan', 'area_code' => '5704', 'slug' => $this->slugit('Kaplan')],
            ['county_name' => 'Vermilion', 'name' => 'Maurice', 'area_code' => '5705', 'slug' => $this->slugit('Maurice')],
            ['county_name' => 'Vermilion', 'name' => 'Gueydan', 'area_code' => '5706', 'slug' => $this->slugit('Gueydan')],
            ['county_name' => 'Vermilion', 'name' => 'Hospital Service District #1', 'area_code' => '5707', 'slug' => $this->slugit('Hospital Service District #1')],
            ['county_name' => 'Vermilion', 'name' => 'Hospital Sales Tax District No 2', 'area_code' => '5708', 'slug' => $this->slugit('Hospital Sales Tax District No 2')],
            ['county_name' => 'Vernon', 'name' => 'Leesville', 'area_code' => '5803', 'slug' => $this->slugit('Leesville')],
            ['county_name' => 'Vernon', 'name' => 'Rosepine', 'area_code' => '5804', 'slug' => $this->slugit('Rosepine')],
            ['county_name' => 'Vernon', 'name' => 'New Llano', 'area_code' => '5805', 'slug' => $this->slugit('New Llano')],
            ['county_name' => 'Vernon', 'name' => 'Hornbeck', 'area_code' => '5806', 'slug' => $this->slugit('Hornbeck')],
            ['county_name' => 'Washington', 'name' => 'Franklinton', 'area_code' => '5901', 'slug' => $this->slugit('Franklinton')],
            ['county_name' => 'Washington', 'name' => 'Bogalusa', 'area_code' => '5902', 'slug' => $this->slugit('Bogalusa')],
            ['county_name' => 'Washington', 'name' => 'Angie', 'area_code' => '5903', 'slug' => $this->slugit('Angie')],
            ['county_name' => 'Washington', 'name' => 'Washington Parish Ward 4', 'area_code' => '5904', 'slug' => $this->slugit('Washington Parish Ward 4')],
            ['county_name' => 'Washington', 'name' => 'Varnado', 'area_code' => '5905', 'slug' => $this->slugit('Varnado')],
            ['county_name' => 'Washington', 'name' => 'Sales Tax District #2', 'area_code' => '5906', 'slug' => $this->slugit('Sales Tax District #2')],
            ['county_name' => 'Webster', 'name' => 'Minden', 'area_code' => '6001', 'slug' => $this->slugit('Minden')],
            ['county_name' => 'Webster', 'name' => 'Cotton Valley', 'area_code' => '6002', 'slug' => $this->slugit('Cotton Valley')],
            ['county_name' => 'Webster', 'name' => 'Springhill', 'area_code' => '6003', 'slug' => $this->slugit('Springhill')],
            ['county_name' => 'Webster', 'name' => 'Cullen', 'area_code' => '6004', 'slug' => $this->slugit('Cullen')],
            ['county_name' => 'Webster', 'name' => 'Sarepta', 'area_code' => '6005', 'slug' => $this->slugit('Sarepta')],
            ['county_name' => 'Webster', 'name' => 'Sibley', 'area_code' => '6006', 'slug' => $this->slugit('Sibley')],
            ['county_name' => 'Webster', 'name' => 'Dixie Inn', 'area_code' => '6007', 'slug' => $this->slugit('Dixie Inn')],
            ['county_name' => 'Webster', 'name' => 'Dixie Inn Tax Dist #6', 'area_code' => '6008', 'slug' => $this->slugit('Dixie Inn Tax Dist #6')],
            ['county_name' => 'Webster', 'name' => 'Parish Area Within Dist #6', 'area_code' => '6009', 'slug' => $this->slugit('Parish Area Within Dist #6')],
            ['county_name' => 'West Carroll', 'name' => 'Oak Grove', 'area_code' => '6201', 'slug' => $this->slugit('Oak Grove')],
            ['county_name' => 'West Carroll', 'name' => 'Village Of Epps', 'area_code' => '6202', 'slug' => $this->slugit('Village Of Epps')],
            ['county_name' => 'West Feliciana', 'name' => 'Town Of St. Francisville', 'area_code' => '6301', 'slug' => $this->slugit('Town Of St. Francisville')],
            ['county_name' => 'Winn', 'name' => 'Winnfield', 'area_code' => '6401', 'slug' => $this->slugit('Winnfield')]
        ];
    }

}
