<?php

namespace Thirty98\Seeder\States\Louisiana;

use Thirty98\API\Stdlib\AbstractDatabaseSeeder;

class VehicleFeeSeeder extends AbstractDatabaseSeeder
{
    public $state_code = 'LA';
    protected $table_name = 'cities_fees';

    protected function executeSeeder()
    {
        // $state = DB::table('states')->where('code', $this->state_code)->first();
        // $result = $this->getFeesByState("LA");

        // var_dump($result);

        /*foreach ($this->getVehicleFees() AS $vehicleFee) {
            var_dump($vehicleFee);
            $exists = DB::table($this->table_name)->where('code', $county['code'])
                ->where('state_id', $state->id)
                ->first();

            if (!$exists) {
                DB::table($this->table_name)->insert(array_merge(['state_id' => $state->id], $county));
            }

            continue;
        }*/
    }

    protected function getVehicleFees()
    {
        return [
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'trailer-1y license', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'trailer-4y license', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'semi-trailer', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'PERSNL_PLATE_FEE', 'amount' => '25.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'PERSL_PLATE_ADMIN_FEE', 'amount' => '3.50'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'PERSL_PLATE_HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => '1-Yr Commercial Plate', 'amount' => '10.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => '2-Yr Commercial Plate', 'amount' => '20.00'],
            ['category' => 'van', 'type' => 'van', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'PERSNL_PLATE_FEE', 'amount' => '25.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'PERSL_PLATE_ADMIN_FEE', 'amount' => '3.50'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'PERSL_PLATE_HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => '1-Yr Commercial Plate', 'amount' => '10.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => '2-Yr Commercial Plate', 'amount' => '20.00'],
            ['category' => 'SUV', 'type' => 'SUV', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'truck-tractor', 'type' => 'truck-tractor', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'LICENSE_FEE', 'amount' => '25.00'],
            ['category' => 'bus', 'type' => 'private-bus', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'LICENSE_FEE', 'amount' => '12.00'],
            ['category' => 'off-road', 'type' => 'off-road-vehicle', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'LICENSE_FEE', 'amount' => '25.00'],
            ['category' => 'collector-vehicle', 'type' => 'collector-vehicle', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            /*Lousiana Static Values - to be inserted to states_fees*/
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'PERSNL_PLATE_FEE', 'amount' => '25.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'PERSL_PLATE_ADMIN_FEE', 'amount' => '3.50'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'PERSL_PLATE_HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => '1-Yr Commercial Plate', 'amount' => '10.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => '2-Yr Commercial Plate', 'amount' => '20.00'],
            ['category' => 'car', 'type' => 'car', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'truck', 'type' => 'truck', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'commercial', 'type' => 'commercial', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'recreational', 'type' => 'motor-home', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'PERSNL_PLATE_FEE', 'amount' => '25.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'PERSL_PLATE_ADMIN_FEE', 'amount' => '3.50'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'PERSL_PLATE_HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'motorcycle', 'type' => 'motorcycle', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'trailer', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'utility-trailer', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],

            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'TITLE_CORRECTION_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'HANDLING_FEE', 'amount' => '8.00'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'REG_DUP_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'LICENSE_TRNSFR_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'DUP_TITLE_FEE', 'amount' => '68.50'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'DUP_PLATE_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'LICENSE_PNLTY_FEE', 'amount' => '3.00'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'LICENSE_DUP_FEE', 'amount' => '12.00'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'NOTARY_FEE', 'amount' => '20.00'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'CONVENIENCE_FEE', 'amount' => '18.00'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'PROCESSING_FEE', 'amount' => '37.00'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'MAIL_FEE', 'amount' => '10.00'],
            ['category' => 'trailer', 'type' => 'boat-trailer', 'state' => 'LA', 'fee' => 'ELECTRONIC_FILING_FEE', 'amount' => '10.00'],
        ];
    }

}
